import type { LegalSection } from '../legalContentTypes';

export const TERMS_BODY_SECTIONS: LegalSection[] = [
  {
    id: 'definitions',
    title: '1. Definitions',
    blocks: [
      {
        type: 'p',
        content: [
          'In addition to terms defined elsewhere in this Agreement, the following terms have the following meanings:',
        ],
        k: 'b0',
      },
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.1. Admin Account',
                    bold: true,
                    k: 'r0',
                  },
                  ' means the Account that the Customer registers with signing up to the service and that has the most comprehensive rights including creating new Users.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.2. Agreement',
                    bold: true,
                    k: 'r0',
                  },
                  ' means the contract concluded with the Customer under these Yosemite Crew License and Subscription Terms and its Appendices.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i2',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.3. Business Owner',
                    bold: true,
                    k: 'r0',
                  },
                  ' means a Customer registering as a Business Owner who can interact with Pet Owners',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i3',
            blocks: [
              {
                type: 'text',
                content: [
                  '1.4. Customer means any company having entered or about to enter into a contractual relationship with DuneXploration in order to allow Users (typically its employees) the use of the SaaS Service and/or the Software.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i4',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.5. Customer Data',
                    bold: true,
                    k: 'r0',
                  },
                  ' means all content and data, including but not limited to personal data, either provided by the Customer or entered on its behalf, through use of the SaaS Services or collected or generated by the SaaS Services on behalf of the Customer, and which remains in DuneXploration’s possession and control as part of the SaaS Services.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i5',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.6. Data Subject',
                    bold: true,
                    k: 'r0',
                  },
                  ' means any identified or identifiable natural person in accordance with the definitions of the GDPR.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i6',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.7. Developer',
                    bold: true,
                    k: 'r0',
                  },
                  ' means a Customer registering as a Developer to sell plugins on the Digital Marketplace to Business Owners.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i7',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.8. Digital Marketplace',
                    bold: true,
                    k: 'r0',
                  },
                  ' means the online platform that allows Developers the selling of plugins to Business Owners.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i8',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.9. Documentation',
                    bold: true,
                    k: 'r0',
                  },
                  ' means any technical specification documentation, technical product descriptions, user guides and technical integration guides relating to the SaaS Services.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i9',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.10. DPA',
                    bold: true,
                    k: 'r0',
                  },
                  ' means DuneXploration’s data processing agreement agreed between DuneXploration and Customers as attached in Exhibit B.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i10',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.11. DuneXploration',
                    bold: true,
                    k: 'r0',
                  },
                  ' means the DuneXploration UG (haftungsbeschränkt), Am Finther Weg 7, 55127 Mainz.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i11',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.12. Intellectual Property',
                    bold: true,
                    k: 'r0',
                  },
                  ' means all rights of intellectual property, such as copyrights, trademark rights, patents, model rights, trade name rights, database rights and neighbouring rights, as well as domain names and know-how and any related rights.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i12',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.13. Mobile App',
                    bold: true,
                    k: 'r0',
                  },
                  ' means the application for Pet Owners, Customer and Users that gives Customer access to the SaaS Services from a mobile device and provides Pet Owners access to services of Business Owners and certain functions such as booking appointments.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i13',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.14. Pet Owner',
                    bold: true,
                    k: 'r0',
                  },
                  ' means a person using the Mobile App to manage their pets and book appointments or services at a Business Owner.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i14',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.15. SaaS Access Rights',
                    bold: true,
                    k: 'r0',
                  },
                  ' means type and quantity of SaaS access rights granted to the Customer for use during the applicable Subscription Term.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i15',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.15. SaaS Services',
                    bold: true,
                    k: 'r0',
                  },
                  ' means the online service Yosemite Crew, a Practice Information Management System (“PIMS”, also referred to as the “PMS”) for Business Owners and a platform for Developers to offer plugins to Business Owners including all its functions and all SaaS Access Rights offered by DuneXploration.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i16',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.17. Services',
                    bold: true,
                    k: 'r0',
                  },
                  ' means the SaaS Services and the Additional Services (if any) together.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i17',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.18. Software',
                    bold: true,
                    k: 'r0',
                  },
                  ' means the Self Hosting Version of the PIMS provided under an Open Source Software License.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i18',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.19. Subscription Term',
                    bold: true,
                    k: 'r0',
                  },
                  ' means the Initial Subscription Term plus any Renewal Term(s).',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i19',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.20. Support Services',
                    bold: true,
                    k: 'r0',
                  },
                  ' means the Services provided under the Support Services and Service Levels Policy.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i20',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.21. These Terms',
                    bold: true,
                    k: 'r0',
                  },
                  ' means these Yosemite Crew License and Subscription Terms.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i21',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.22. User',
                    bold: true,
                    k: 'r0',
                  },
                  ' means any user that is created by the Customer in the Admin Account irrespective of his or her role.tore it.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i22',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '1.23. Third-Party Trademarks',
                    bold: true,
                    k: 'r0',
                  },
                  ' This repository may reference or include integrations, plugins, names, logos, or trademarks of third-party companies (including but not limited to IDEXX, MSD Veterinary Manual, and other partners). Such trademarks and logos are the property of their respective owners and are used solely for identification or interoperability purposes. Nothing in this repository grants any right or license to use any third-party trademarks, logos, or branding except as permitted by the respective owners.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b1',
      },
    ],
  },
  {
    id: 'scope',
    title: '2. Scope',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '2.1.',
                    bold: true,
                    k: 'r0',
                  },
                  ' These Terms shall apply to and control solely with respect to the Services. In the event of a conflict between these Terms and any other terms and conditions and/or Appendices of the Agreement, these Terms shall prevail with respect to the SaaS Services, unless explicitly provided otherwise.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '2.2.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Licensing of the Software is not covered by these Terms but only governed by the applicable Open Source Software license.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i2',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '2.3.',
                    bold: true,
                    k: 'r0',
                  },
                  ' DuneXploration rejects any and all terms and conditions of Customers. Only these Terms apply to the respective contractual relationships with DuneXploration.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i3',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '2.4.',
                    bold: true,
                    k: 'r0',
                  },
                  ' In the event of a conflict between these Terms and an individual agreement between DuneXploration and a Customer, the individual agreement shall prevail, unless explicitly provided otherwise in these Terms.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'overview',
    title: '3. Overview of the SaaS Services',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '3.1.',
                    bold: true,
                    k: 'r0',
                  },
                  ' DuneXploration operates a SaaS Service that provides Business Owners with a flexible and scalable PIMS. The PIMS is able to provide Business Owners with functions to manage their professional veterinary practice and services. For Developers the SaaS Service provides the necessary tools to offer plugins on a Digital Marketplace to Business Owners.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '3.2.',
                    bold: true,
                    k: 'r0',
                  },
                  ' A separate Mobile App is available to Pet Owners, Customer and Users that gives Customer access to the SaaS Services on a mobile device and provides Pet Owners access to services of Business Owners and certain functions such as booking appointments. The Mobile App is provided by DuneXploration separately and guided by separate terms and conditions.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i2',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '3.3.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The SaaS Service can be used in different countries and languages. The SaaS Service is available anywhere with a good internet connection.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'account',
    title: '4. Conclusion of the Agreement and registering for an account',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '4.1.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The Customer has to register to use the SaaS Service. Registering is free of charge for the Customer.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '4.2.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The Customer can register directly by visiting the website ',
                  {
                    text: 'www.yosemitecrew.com',
                    href: 'https://www.yosemitecrew.com',
                    k: 'r1',
                  },
                  ' by creating an Admin Account. The person registering the Admin Account for the Customer confirms that he or she has the necessary legal power and capacity to act on Customer’s behalf and conclude the Agreement.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i2',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '4.3.',
                    bold: true,
                    k: 'r0',
                  },
                  ' By clicking on “Sign Up”, the Customer asks DuneXploration to create an Admin Account on the Platform and DuneXploration will send an email with a legally binding offer to open the Admin Account and to confirm the Customer’s email address. By clicking on “confirm email”, the Customer accepts the offer, concludes the contract with DuneXploration and opens the Admin Account.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i3',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '4.4.',
                    bold: true,
                    k: 'r0',
                  },
                  ' After the sign up, Customer has to provide certain basic information, including its place of business, business registration number and an address and further information depending on if the Customer is a Business Owner or a Developer. The Customer can rectify all and any information at any time during sign up and later in the settings of the Admin Account.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i4',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '4.5.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Customer shall keep all account information, and especially the chosen password, confidential and not disclose it to any third party. Any abuse or suspected abuse shall be reported to DuneXploration immediately.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i5',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '4.6.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The User can access these terms anytime on the SaaS Service in the most recent version. The Agreement is concluded in English and These Terms are available in English exclusively.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'pms-functions',
    title: '5. Functions of the PIMS',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '5.1.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The PIMS provides Business Owners with the necessary functions to manage their veterinary practice or other veterinary professional services. The functions of the PIMS include, depending on the chosen type of business:',
                ],
                k: 'b0',
              },
              {
                type: 'ul',
                items: [
                  {
                    k: 'i0',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '5.1.1.',
                            bold: true,
                            k: 'r0',
                          },
                          ' An overview of all relevant metrics of their business',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i1',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '5.1.2.',
                            bold: true,
                            k: 'r0',
                          },
                          ' The ability to manage Users',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i2',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '5.1.3.',
                            bold: true,
                            k: 'r0',
                          },
                          ' Options regarding the visibility of the clinic',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i3',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '5.1.4.',
                            bold: true,
                            k: 'r0',
                          },
                          ' The ability to manage appointments',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i4',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '5.1.5.',
                            bold: true,
                            k: 'r0',
                          },
                          ' Role and permission management',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i5',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '5.1.6.',
                            bold: true,
                            k: 'r0',
                          },
                          ' Inventory and procedure management',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i6',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '5.1.7.',
                            bold: true,
                            k: 'r0',
                          },
                          ' Billing and invoicing',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                ],
                k: 'b1',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '5.2.',
                    bold: true,
                    k: 'r0',
                  },
                  ' DuneXploration reserves the right to add, remove or modify functions from the PIMS in the future but will ensure that the core functions of the PIMS mentioned above will be available to Customer. It will notify Customer of changes.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'developer-functions',
    title: '6. Functions for Developers',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '6.1.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Developers can use the SaaS Service to develop plugins for the PIMS and sell them to Business Owners on the Digital Marketplace.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '6.2.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The Digital Marketplace is still under development and details will be added in the future.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'pet-owner-services',
    title: '7. Offering services to Pet Owners',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '7.1.',
                    bold: true,
                    k: 'r0',
                  },
                  ' If Business Owners decide to make their services visible for all Pet Owners on the Mobile App (for example booking appointments but also to provide other services such as diabetes assessments), the following provisions to fulfil our obligations from the REGULATION (EU) 2019/1150 on promoting fairness and transparency for business users of online intermediation services (“P2B Regulation”) applies. With regard to the obligations from the P2B Regulations DuneXploration gives Customer the following information:',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '7.2. Access to Data',
                    bold: true,
                    k: 'r0',
                  },
                ],
                k: 'b0',
              },
              {
                type: 'ul',
                items: [
                  {
                    k: 'i0',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '7.2.1.',
                            bold: true,
                            k: 'r0',
                          },
                          ' Access to Customer Data by DuneXploration ',
                          {
                            br: true,
                            k: 'r1',
                          },
                          ' Since DuneXploration operates the SaaS Service it can access any Customer Data (including User and Pet Owner data). This includes, in particular, the following categories of data:',
                        ],
                        k: 'b0',
                      },
                      {
                        type: 'ul',
                        items: [
                          {
                            k: 'i0',
                            blocks: [
                              {
                                type: 'text',
                                content: ['Contact Details'],
                                k: 'b0',
                              },
                            ],
                          },
                          {
                            k: 'i1',
                            blocks: [
                              {
                                type: 'text',
                                content: ['Pet data'],
                                k: 'b0',
                              },
                            ],
                          },
                          {
                            k: 'i2',
                            blocks: [
                              {
                                type: 'text',
                                content: ['Accounting data'],
                                k: 'b0',
                              },
                            ],
                          },
                          {
                            k: 'i3',
                            blocks: [
                              {
                                type: 'text',
                                content: [
                                  'Booked appointments or services rendered and any related data and',
                                ],
                                k: 'b0',
                              },
                            ],
                          },
                          {
                            k: 'i4',
                            blocks: [
                              {
                                type: 'text',
                                content: ['Usage data.'],
                                k: 'b0',
                              },
                            ],
                          },
                        ],
                        k: 'b1',
                      },
                      {
                        type: 'text',
                        content: [
                          'A comprehensive List of data processed for Customer can be found in Appendix 1 Annex 2 of the DPA. Access to such data is granted solely for the purposes of operating, improving, and securing the SaaS Services, ensuring compliance with applicable law, and supporting Business Owners in the provision of their services.',
                        ],
                        k: 'b2',
                      },
                    ],
                  },
                  {
                    k: 'i1',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '7.2.2.',
                            bold: true,
                            k: 'r0',
                          },
                          ' Access to Customer Data by Business Owners Each Business Owner has access to all Customer Data they have provided to DuneXploration in the context of using the SaaS Service and to the data that is generated through the provision of the SaaS Service. Access is granted via the functions of the SaaS Service. With regard to the services offered to all Pet Owners this includes, in particular, the following categories of data:',
                        ],
                        k: 'b0',
                      },
                      {
                        type: 'ul',
                        items: [
                          {
                            k: 'i0',
                            blocks: [
                              {
                                type: 'text',
                                content: ['Contact Details'],
                                k: 'b0',
                              },
                            ],
                          },
                          {
                            k: 'i1',
                            blocks: [
                              {
                                type: 'text',
                                content: [
                                  'Booked appointments or services rendered and any related data',
                                ],
                                k: 'b0',
                              },
                            ],
                          },
                          {
                            k: 'i2',
                            blocks: [
                              {
                                type: 'text',
                                content: ['Pet data'],
                                k: 'b0',
                              },
                            ],
                          },
                          {
                            k: 'i3',
                            blocks: [
                              {
                                type: 'text',
                                content: ['Billing information.'],
                                k: 'b0',
                              },
                            ],
                          },
                        ],
                        k: 'b1',
                      },
                      {
                        type: 'text',
                        content: [
                          'A comprehensive List of data processed for Customer can be found in Appendix 1 Annex 2 of the DPA.',
                        ],
                        k: 'b2',
                      },
                    ],
                  },
                  {
                    k: 'i2',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '7.2.3.',
                            bold: true,
                            k: 'r0',
                          },
                          ' Access to Data provided by or generated by other Customers or Pet Owners: Business Owners do not access data of other Customers or Pet Owners.',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i3',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '7.2.4.',
                            bold: true,
                            k: 'r0',
                          },
                          ' Disclosure of Data to Third Parties: Other than Customer Data made public to Pet Owners or Developers, DuneXploration only shares Customer Data with technical service providers listed in the Data Processing Agreement.',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                ],
                k: 'b1',
              },
            ],
          },
          {
            k: 'i2',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '7.3.1 Main Parameters Used for Ranking:',
                    bold: true,
                    k: 'r0',
                  },
                ],
                k: 'b0',
              },
              {
                type: 'ul',
                items: [
                  {
                    k: 'i0',
                    blocks: [
                      {
                        type: 'text',
                        content: ['Services offered by Customer'],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i1',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          'If relevant for the Service (for example for booking appointments the Customer’s Location (e.g., proximity to the Pet Owner’s search location);',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i2',
                    blocks: [
                      {
                        type: 'text',
                        content: ['Service hours'],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i3',
                    blocks: [
                      {
                        type: 'text',
                        content: ['User ratings'],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i4',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          'Business Name (e.g., alphabetical order or match with search terms). These parameters are considered to ensure relevant, (where applicable) localized, and easily identifiable results for Pet Owners.',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i5',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          'Pet Owners have at the moment the following filters to modify their search for services:',
                        ],
                        k: 'b0',
                      },
                      {
                        type: 'ul',
                        items: [
                          {
                            k: 'i0',
                            blocks: [
                              {
                                type: 'text',
                                content: ['Previous'],
                                k: 'b0',
                              },
                            ],
                          },
                          {
                            k: 'i1',
                            blocks: [
                              {
                                type: 'text',
                                content: ['Vet New Vet'],
                                k: 'b0',
                              },
                            ],
                          },
                        ],
                        k: 'b1',
                      },
                    ],
                  },
                ],
                k: 'b1',
              },
            ],
          },
          {
            k: 'i3',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '7.3.2.Relative Weighting of Parameters:',
                    bold: true,
                    k: 'r0',
                  },
                  ' Among the above parameters, (if relevant) location is typically given higher weight than name, as geographic preference plays a more significant role for Pet Owner.  If location is not relevant the service hours are the most relevant factor.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i4',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '7.3.3. Influence of Payments on Ranking:',
                    bold: true,
                    k: 'r0',
                  },
                  ' Customers cannot influence their ranking through direct or indirect payments to DuneXploration. No payment-based ranking advantages are offered or applied.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i5',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '7.3.4. Product or Service Characteristics and Consumer Relevance:',
                    bold: true,
                    k: 'r0',
                  },
                  ' The ranking mechanism may also take into account certain characteristics of the services offered, including relevance to consumer preferences based on prior search behaviour or explicitly provided filters. However, these aspects play a secondary role in the default ranking logic.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i6',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '7.4.Retention of Data',
                    bold: true,
                    k: 'r0',
                  },
                ],
                k: 'b0',
              },
              {
                type: 'ul',
                items: [
                  {
                    k: 'i0',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '7.4.1.',
                            bold: true,
                            k: 'r0',
                          },
                          ' After termination of the Agreement, DuneXploration does not retain any identifiable Customer Data.',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i1',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '7.4.2.',
                            bold: true,
                            k: 'r0',
                          },
                          ' However, DuneXploration may retain Customer Data in aggregated and anonymized form, provided such data cannot be traced back to a Customer or Data Subject. This aggregated data may be used for statistical analysis, service improvement, or market research purposes.',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i2',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '7.4.3.',
                            bold: true,
                            k: 'r0',
                          },
                          ' Customer Access: The Customer has no access to any data after termination of the Agreement.',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                ],
                k: 'b1',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'our-responsibilities',
    title: '8. DuneXploration’s responsibilities',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '8.1.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Subject to any other individual agreement with the Customer, DuneXploration provides the technical resources for the SaaS Service and allows Users to use the Yosemite Crew Platform as described in these Terms.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '8.2.',
                    bold: true,
                    k: 'r0',
                  },
                  " DuneXploration provides the SaaS Services on servers up to the access point of DuneXploration's data center (“Service Delivery Point”). The Customer is responsible for maintaining its own internet access to reach the Service Delivery Point.",
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i2',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '8.3.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Service levels are specified in ',
                  {
                    text: 'Exhibit A – Support Services and Service Level Policy.',
                    bold: true,
                    k: 'r1',
                  },
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i3',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '8.4.',
                    bold: true,
                    k: 'r0',
                  },
                  ' As part of the SaaS Services, DuneXploration will provide Support Services. In addition to establishing and maintaining the hosted environment of the SaaS Services, DuneXploration will maintain the components of the SaaS Services with all current updates that DuneXploration deems necessary for the SaaS Services. DuneXploration will use commercially reasonable efforts to implement any required error corrections or other necessary fixes for the SaaS Services.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i4',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '8.5.',
                    bold: true,
                    k: 'r0',
                  },
                  ' As a part of the SaaS Services, DuneXploration will also maintain a backup of all Customer Data that DuneXploration is required to retain as a part of the SaaS Services. In the event the Customer Data becomes destroyed or corrupt, DuneXploration shall use commercially reasonable efforts to restore all available data from backup, and to remediate and recover such corrupt data.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'access-rights',
    title: '9. SaaS access rights and licenses',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '9.1.',
                    bold: true,
                    k: 'r0',
                  },
                  ' During the Subscription Term, DuneXploration grants to the Customer, solely for the Customer’s internal business use and subject to the limitations and restrictions set in these Terms, a non-exclusive, non-transferable, non-sublicensable right to use the SaaS Services. With respect to the Documentation applicable to the SaaS Services, the Customer may make a reasonable number of copies of the Documentation solely as needed for the Customer’s and its Affiliates’ internal business purposes.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '9.2.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The Customer acknowledges and agrees that the use rights provided hereunder do not grant any rights not explicitly expressed. All other such rights and interests in DuneXploration’s Intellectual Property (including any derivatives thereto) are expressly reserved and remain vested in DuneXploration.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i2',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '9.3.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Except as otherwise specified in an Addendum, expressly permitted in writing by DuneXploration, or otherwise cannot be precluded under mandatory applicable law, Customer shall not, and shall not permit any other party to:',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i3',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '9.4.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Disassemble, decompile, decrypt, or reverse engineer, or attempt to discover or reproduce source code for any part of the SaaS Services or on-premise components; adapt, modify, or prepare derivative works based on any of DuneXploration’s Intellectual Property; or use any of DuneXploration’s Intellectual Property to create any program or material that performs, replicates, or utilizes the same or substantially similar functions as the SaaS Service.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i4',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '9.5.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Alter, remove, or suppress any copyright, confidentiality, or other proprietary notices, marks, or legends placed on or embedded in DuneXploration Intellectual Property, or fail to ensure that such notices and legends appear on all full or partial copies of DuneXploration Intellectual Property or any related material.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i5',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '9.6.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Sell, sublicense, lease, assign, delegate, transfer, distribute, encumber, or otherwise transform any DuneXploration Intellectual Property or any of the rights or obligations granted to or imposed on the Customer hereunder.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'customer-obligations',
    title: '10. Customer’s obligations',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '10.1.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Customer allocates User Accounts to its employees in accordance with the license purchased.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '10.2.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Customer must ensure that their use of the SaaS Service fulfills all applicable statutory requirements, such as maintaining a proper license, compliance with consumer protection law, data protection law, and statutory information obligations (e.g., maintaining an imprint). DuneXploration is not responsible for any breach of such statutory provisions by the Customer.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i2',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '10.3.',
                    bold: true,
                    k: 'r0',
                  },
                  ' If the SaaS Services have an error or malfunction, the Customer shall immediately notify DuneXploration thereof in accordance with the provisions of Exhibit A — SUPPORT SERVICES AND SERVICE LEVEL POLICY.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i3',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '10.4.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The Customer is responsible for ensuring that all Users comply with these Terms by monitoring and instructing its Users accordingly. In particular, the Customer shall:',
                ],
                k: 'b0',
              },
              {
                type: 'ul',
                items: [
                  {
                    k: 'i0',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          'explicitly inform its Users that the SaaS Services may only be used in a professional context and only for professional matters;',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i1',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          'instruct its Users not to use the SaaS Services for illegal purposes, in particular not to harm third parties or DuneXploration. Customer will also not carry out any such actions itself;on.',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i2',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          "not use the SaaS Services in a way that compromises the security, proper functioning and integrity of DuneXploration's systems or that circumvents or compromises security measures. In particular, the Customer will instruct their Users not to generate malicious, harmful prompts or to carry out prompt injection attacks in order to manipulate the behavior of the SaaS Services, or to carry out vulnerability, penetration or similar tests;",
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i3',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          'not to pass off output generated by means of the SaaS Services as having been created by a human, and not to use the output if there is reason to believe that the use of the output could infringe the rights of third parties.',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                ],
                k: 'b1',
              },
            ],
          },
          {
            k: 'i4',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '10.5.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The Customer shall ensure and inform Users about the acceptable use of the SaaS Services as specified in these Terms.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'technical-dependencies',
    title: '11. Technical dependencies and limitations',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  'In order to use the SaaS Services, Users need to meet the following technical requirements:',
                ],
                k: 'b0',
              },
              {
                type: 'ul',
                items: [
                  {
                    k: 'i0',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          'Current versions of Windowsand MacOS Xare fully supported (“Supported Operating Systems”).',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i1',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          'Current versions of Chrome, Firefox, Safari, or Edgeare fully supported (“Supported Browsers”).',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i2',
                    blocks: [
                      {
                        type: 'text',
                        content: ['A sufficient network broadband connectionis required.'],
                        k: 'b0',
                      },
                    ],
                  },
                ],
                k: 'b1',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'acceptable-use',
    title: '12. Acceptable use policy',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '12.2.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The Customer may not use the SaaS Services in a way that unnecessarily interferes with the normal operation of the SaaS Services generally.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '12.3.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The Customer is responsible for maintaining the confidentiality and security of all passwords issued, and for ensuring that each password is only used by the individual(s) authorised. To the extent DuneXploration enables the Customer with administrative rights to create passwords for its personnel, the Customer shall be responsible for issuing such passwords.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i2',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '12.4.',
                    bold: true,
                    k: 'r0',
                  },
                  ' If the Customer violates the acceptable use policy set forth in this Section, DuneXploration may require the Customer to immediately abstain from any such action or behaviour, provided that DuneXploration may also terminate this Agreement for cause with or without notice if the violation(s) of the acceptable use policy are, decided in DuneXploration’s sole discretion, of such gravity as to justify such termination. In such case DuneXploration will give Customer sufficient time (at least 30 days) to',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i3',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '12.5.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The Customer shall use the SaaS Services professionally and lawfully. In particular, the Customer may not attempt prompt-injection attacks against the SaaS Services, nor pass off output generated by the SaaS Services as human-made.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'fees',
    title: '13. Fees',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '13.1.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The Customer shall pay DuneXploration a fee for rendering the Services. The calculation depends on several factors and is described on the website.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '13.2.',
                    bold: true,
                    k: 'r0',
                  },
                  ' DuneXploration shall invoice the Customer according to the criteria in Section 13.1 to Section 13.3 at the end of each month.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i2',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '13.3.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Customer shall pay all Subscription Fees with the payment method specified in the Admin Account.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i3',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '13.4.',
                    bold: true,
                    k: 'r0',
                  },
                  ' All amounts due to DuneXploration hereunder are net amounts, exclusive of, and the Customer is responsible for paying, all value added taxes or other similar taxes. DuneXploration will issue its invoices in accordance with the applicable laws and may thus, as the case may be, also invoice the payable value added taxes.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i4',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '13.5.',
                    bold: true,
                    k: 'r0',
                  },
                  ' DuneXploration is entitled to increase the prices the fee is calculated on for the first time after the expiry of 12 months following the start of the contract provided that DuneXploration’s costs for the provision of the SaaS Service have increased by at least 20% compared to the same month of the previous year. DuneXploration shall communicate the increase in writing (email to suffice) at least 2 months before the increase shall come into force. The Customer has the right to terminate the Agreement within a period of 30 days after receiving the notice. DuneXploration shall inform the customer of the termination right together with each notification of a price increase. CUSTOMER DATA',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i5',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '13.6.',
                    bold: true,
                    k: 'r0',
                  },
                  ' DuneXploration acknowledges it receives no ownership or, except to the extent specified herein and in Section 10.2, other rights in any Customer Data, and all rights, title and interest in such Customer Data remain with Customer. DuneXploration shall not, and shall not permit its Personnel to use or disclose Customer Data, unless authorized by the terms and conditions of this Addendum, by the Customer in writing, or if DuneXploration is required to do so by law or court order.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i6',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '13.7.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Customer agrees that DuneXploration may:',
                ],
                k: 'b0',
              },
              {
                type: 'ul',
                items: [
                  {
                    k: 'i0',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          '(a) use and disclose in aggregate, anonymous and de-identified form, information derived from Customer Data where the resulting information does not in any way identify or allow the identification of Customer or any Personal Data, and',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i1',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          '(b) access, use in accordance with the terms and conditions of this Addendum, but not otherwise use or disclose, Customer Data for DuneXploration’s internal business purposes, including for purposes of planning, support, administration and invoicing related to Customer’s use of the SaaS Services, improving or creating new offerings related to the SaaS Services.',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                ],
                k: 'b1',
              },
              {
                type: 'text',
                content: [
                  'Customer acknowledges that DuneXploration owns all right, title and interest in and to the aggregated data. The Customer instructs DuneXploration within the framework of the DPA to anonymize the personal data for the aforementioned use.',
                ],
                k: 'b2',
              },
            ],
          },
          {
            k: 'i7',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '13.8.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Customer agrees that Customer is solely responsible for:',
                ],
                k: 'b0',
              },
              {
                type: 'ul',
                items: [
                  {
                    k: 'i0',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          '(i) obtaining any Customer Data and other information Customer provides while using the SaaS Services,',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i1',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          '(ii) obtaining all rights and consents necessary to collect, retain, use and disclose the Customer Data,',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i2',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          '(iii) ensuring the Processing, collection, retention and any other processing of Personal Data in connection with the use and delivery of the SaaS Services does not violate the rights of Data Subjects or the Privacy Laws,',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i3',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          '(iv) establishing and complying with a retention schedule and destruction guidelines related to Customer Data where required by law,',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i4',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          '(v) the accuracy, completeness, quality, integrity, legality, reliability, appropriateness and copyright of all Customer Data.',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                ],
                k: 'b1',
              },
              {
                type: 'text',
                content: [
                  'By providing any Customer Data or other information, Customer represents and warrants that such information does not:',
                ],
                k: 'b2',
              },
              {
                type: 'ul',
                items: [
                  {
                    k: 'i0',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          '(a) violate any intellectual property rights, publicity rights, confidentiality or trade secret rights, or any other legal or equitable rights;',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i1',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          '(b) violate any law, rule, order, judgment or regulation to which Customer or the Customer Data may be subject; and',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i2',
                    blocks: [
                      {
                        type: 'text',
                        content: ['(c) violate in any way Customer’s obligations.'],
                        k: 'b0',
                      },
                    ],
                  },
                ],
                k: 'b3',
              },
            ],
          },
          {
            k: 'i8',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '13.9.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Customer acknowledges and agrees that DuneXploration is not responsible or liable for any unlawful, harassing, defamatory, privacy invasive, abusive, threatening, offensive, harmful, vulgar, obscene, tortuous, hateful, racially, ethnically or otherwise objectionable information contained in Customer Data, or content, or information or content contained in Customer Data that infringes or may infringe any copyright, patent, moral right, trade secret, confidential information, trademark right or any other right of a third party. DuneXploration may remove any violating content posted on the SaaS Services or transmitted through the SaaS Services, without notice to Customer.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i9',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '13.10.',
                    bold: true,
                    k: 'r0',
                  },
                  ' In addition to all other obligations in this Addendum with respect to Customer Data, each party agrees to comply with its obligations under Privacy Laws, and in the context of any Processing of Personal Data through the provision of the SaaS Services, the Parties shall comply with the DPA in Exhibit 2, which is hereby incorporated into the Agreement.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'warranty',
    title: '14. Warranty',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '14.1.',
                    bold: true,
                    k: 'r0',
                  },
                  ' DuneXploration will meet warranty claims and rights that the Customer may have against DuneXploration in accordance with the applicable statutory provisions, subject only to Sections 15.2 and 15.3.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '14.2.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Claims to reduce the Subscription Fees shall fall under the statute of limitations one year after the end of the calendar year during which the claims came into existence and the Customer knew or should have reasonably known the factual circumstances that gave rise to the claim.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i2',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '14.3.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Damage claims are subject to the provision of Section 16.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i3',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '14.4.',
                    bold: true,
                    k: 'r0',
                  },
                  ' DuneXploration may temporarily restrict access to the SaaS Service in order to carry out maintenance work in accordance with the provision of the  ',
                  {
                    text: 'Exhibit A SUPPORT SERVICES AND SERVICE LEVEL POLICY.',
                    bold: true,
                    k: 'r1',
                  },
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'liability',
    title: '15. Limitation of liability',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '15.1.',
                    bold: true,
                    k: 'r0',
                  },
                  ' DuneXploration shall be liable in accordance with the applicable statutory provisions (whether in contract, tort or otherwise) for damages suffered by the Customer that (i) have been caused as a result of DuneXploration, its legal representatives, its agents or auxiliaries having acted, or having failed to act where there was a duty for DuneXploration to act, in gross negligence or with wilful or malicious intent; (ii) have occurred as a result of a breach of a guarantee (the term “guarantee” in accordance with the applicable statutory meaning); (iii) are a result of a culpably caused injury to life, limb or health; and/or (iv) are subject to product liability under the German Product Liability Act.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '15.2.',
                    bold: true,
                    k: 'r0',
                  },
                  ' In cases of negligence other than gross negligence, DuneXploration shall only be liable for damages that result from breaches of material contractual obligations. This limitation of liability shall not apply, however, where the damages result from culpably caused injuries to life, limb or health or a breach of a guarantee (as defined in Section 15.1). “Material contractual obligations” are such contractual obligations that, if breached, jeopardize the aim and purpose of the contract, and are such that the other contractual party may generally rely on.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i2',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '15.3.',
                    bold: true,
                    k: 'r0',
                  },
                  ' In cases of negligence other than gross negligence, DuneXploration’s liability shall also be limited to damages that are typically foreseeable in the context of an agreement such as this Agreement. This limitation of liability shall, however, likewise not apply where the damages result from culpably caused injuries to life, limb or health or a breach of a guarantee (as defined in Section 15.1).',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i3',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '15.4.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Other than in cases that fall under Section 15.1 and (other) cases where the damages result from culpably caused injuries to life, limb or health or a breach of a guarantee (as defined above):',
                ],
                k: 'b0',
              },
              {
                type: 'ul',
                items: [
                  {
                    k: 'i0',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '15.4.1.',
                            bold: true,
                            k: 'r0',
                          },
                          ' DuneXploration shall not be liable for indirect, consequential or special damages.',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i1',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '15.4.2.',
                            bold: true,
                            k: 'r0',
                          },
                          ' DuneXploration’s aggregate liability under this Agreement shall not exceed the greater of: (a) the aggregate Fees paid or payable by the Customer to DuneXploration in the twelve (12) calendar months prior to the event giving rise to the liability; or (b) 5,000 EUR.',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                ],
                k: 'b1',
              },
            ],
          },
          {
            k: 'i4',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '15.5.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Any liability other or beyond the liability provided in Sections 15.1 to 15.3 is excluded.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i5',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '15.6.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The Customer is responsible for ensuring the routine backup of its data. Irrespective of Sections 15.1 to 15.3, if the Customer suffers damages that result from the loss of data, DuneXploration shall in each case only be liable for such damages insofar as the damages could not have been avoided by the Customer carrying out data backups of all relevant data in regular intervals according to good industry practice.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i6',
            blocks: [
              {
                type: 'text',
                content: [
                  'Damage claims, irrespective of their legal origin and nature (contract, tort or other), shall fall under the statute of limitations one year after the end of the calendar year during which the claims came into existence and the Customer knew or should have reasonably known the factual circumstances that gave rise to the claim. The foregoing sentence shall, however, not apply where the damage has been caused by, or has not been remedied with or because of, DuneXploration’s wilful intent, where DuneXploration had maliciously concealed a defect in the Products, in cases of injuries to life, limb or health, and/or where the corresponding claims result from the German Product Liability Act.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'confidentiality',
    title: '16. Confidentiality',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  '16.1. Each Party (the “Receiving Party”) understands that the other Party (the “Disclosing Party”) has disclosed or may disclose information relating to the Disclosing Party’s business (hereinafter referred to as “Confidential Information” of the Disclosing Party). The Receiving Party agrees:',
                ],
                k: 'b0',
              },
              {
                type: 'p',
                content: [
                  '(i) to take reasonable precautions to protect such Confidential Information, and',
                ],
                k: 'b1',
              },
              {
                type: 'p',
                content: [
                  '(ii) not to use (except as expressly permitted herein) or divulge to any third person any such Confidential Information.',
                ],
                k: 'b2',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  '16.2. The Disclosing Party agrees that the foregoing shall not apply with respect to any information after ten years following the disclosure thereof (except Confidential Information that is identified as trade secrets, in which case the foregoing obligations are ongoing) or any information that the Receiving Party can document: (a) is or becomes generally available to the public, (b) was in its possession or known by it prior to receipt from the Disclosing Party, (c) was rightfully disclosed to it without restriction by a third party, (d) was independently developed without use of any Confidential Information of the Disclosing Party, or (e) is required by law to be disclosed, provided that the Receiving Party first provides the Disclosing Party with reasonable prior notice and obtains, or provides the Disclosing Party with an opportunity to obtain, a protective order or confidential treatment of the Proprietary Information.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'name-and-logo',
    title: '17. Use of Customer name and logo',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  'Customer grants DuneXploration a non-exclusive, non-transferable, royalty-free, worldwide license to use, distribute, reproduce and display Customer’s trade name(s), trademarks, and logos (collectively, “Marks”) for use by DuneXploration on its website, in marketing materials and for similar marketing purposes.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'term-and-termination',
    title: '18. Term and termination',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '18.1.',
                    bold: true,
                    k: 'r0',
                  },
                  ' This Agreement shall commence on the Order Effective Date and shall continue for the Initial Subscription Term. The Agreement automatically renews for subsequent Renewal Terms except where a Party provides the other with no less than thirty (30) days’ notice prior to the expiry of the Initial Subscription Term or, as the case may be, the then-current Renewal Term of its intent to not renew.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '18.2.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The rights of the Parties to terminate this Agreement for cause remains unaffected.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i2',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '18.3.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Reasons to terminate for cause are specifically (but not exclusively):',
                ],
                k: 'b0',
              },
              {
                type: 'ul',
                items: [
                  {
                    k: 'i0',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '18.3.1.',
                            bold: true,
                            k: 'r0',
                          },
                          ' A breach of Sections 10 and 12 by Customer; or',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i1',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '18.3.2.',
                            bold: true,
                            k: 'r0',
                          },
                          ' By either party a material breach which has not been cured within thirty (30) days after written notice of such breach; or',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                  {
                    k: 'i2',
                    blocks: [
                      {
                        type: 'text',
                        content: [
                          {
                            text: '18.3.3.',
                            bold: true,
                            k: 'r0',
                          },
                          ' By either party at any time if the other party makes an assignment for the benefit of creditors, or commences or has commenced against it any proceeding in bankruptcy or insolvency;',
                        ],
                        k: 'b0',
                      },
                    ],
                  },
                ],
                k: 'b1',
              },
            ],
          },
          {
            k: 'i3',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '18.4.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Notices of non-renewal as well as termination notices must be made in writing (email to suffice).',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
  {
    id: 'miscellaneous',
    title: '20. Miscellaneous',
    blocks: [
      {
        type: 'ul',
        items: [
          {
            k: 'i0',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '20.1.',
                    bold: true,
                    k: 'r0',
                  },
                  ' This Agreement is governed by, and shall be interpreted in accordance with, the laws of, and directly applicable in, the Federal Republic of Germany, excluding, however, the provisions of the United Nations Convention on Contracts for the International Sale of Goods and any conflict of law provisions that would require the application of the material law of another country.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i1',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '20.2.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Unless otherwise expressly set forth in this Agreement, any provision of this Agreement (including this Section 20.2) may only be amended or waived by a written agreement executed by both Parties.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i2',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '20.3.',
                    bold: true,
                    k: 'r0',
                  },
                  ' Neither Party is entitled to assign, delegate or otherwise transfer any rights, claims or obligations under this Agreement, in whole or in part, without the prior written consent of the other Party except that DuneXploration is entitled to assign this Agreement as a whole, as well as individual rights and claims under this Agreement to an Affiliate of DuneXploration. Section 354a of the German Commercial Code remains unaffected.',
                ],
                k: 'b0',
              },
            ],
          },
          {
            k: 'i3',
            blocks: [
              {
                type: 'text',
                content: [
                  {
                    text: '20.4.',
                    bold: true,
                    k: 'r0',
                  },
                  ' The Parties hereby irrevocably submit to the exclusive jurisdiction of the courts of Mainz, Germany, for all disputes or claims arising out of or in connection with this Agreement made hereunder.',
                ],
                k: 'b0',
              },
            ],
          },
        ],
        k: 'b0',
      },
    ],
  },
];
