/**
 * The schedule row's five columns need roughly 600px, which ran ~160px past a
 * 390px phone - and the Treatment step that renders this component is reached on
 * a phone through `PhoneWorkspaceShell`, so the whole workspace went into a
 * sideways scroll.
 *
 * The template is applied as an INLINE style, so no stylesheet or Tailwind
 * variant can override it and the responsive decision has to be made in the
 * component. That is what these tests pin: which template each breakpoint gets.
 */
import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import InpatientSchedule from '@/app/features/appointments/pages/AppointmentWorkspace/components/InpatientSchedule';
import { PHONE_MEDIA_QUERY } from '@/app/ui/layout/PhoneShell/useIsPhone';
import type { ScheduleTask } from '@/app/features/appointments/types/workspace';

jest.mock('@/app/ui/inputs/Dropdown/LabelDropdown', () => ({
  __esModule: true,
  default: () => <div />,
}));

const TASK: ScheduleTask = {
  id: 'task-1',
  time: '08:00',
  description: 'Post-op wound check',
  category: 'Care',
  assignedToName: 'Priya Raman',
  status: 'UPCOMING',
  autoGenerated: false,
};

const baseProps = {
  tasks: [TASK],
  readOnly: true,
  assigneeOptions: [{ label: 'Priya Raman', value: 'prac-1' }],
  onAddTask: jest.fn(),
  onViewTask: jest.fn(),
  onAssignTask: jest.fn(),
  onStatusChange: jest.fn(),
};

/**
 * `useIsPhone` reads `matchMedia(PHONE_MEDIA_QUERY).matches`. The shared setup
 * polyfill answers `false` to everything, so a phone render has to answer that
 * one query truthfully rather than every query.
 */
const setViewport = (isPhone: boolean) => {
  (globalThis.matchMedia as unknown as jest.Mock).mockImplementation((query: string) => ({
    matches: query === PHONE_MEDIA_QUERY ? isPhone : false,
    media: query,
    onchange: null,
    addListener: jest.fn(),
    removeListener: jest.fn(),
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn(),
  }));
};

/** The row body is the grid that carries the inline template. */
const rowTemplate = (): string => {
  const row = screen.getByText('Post-op wound check').closest('.grid');
  return (row as HTMLElement).style.gridTemplateColumns;
};

describe('InpatientSchedule row template', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  it('keeps the five-column table on desktop', () => {
    setViewport(false);
    render(<InpatientSchedule {...baseProps} />);

    const template = rowTemplate();
    // Timeline gutter aside: category, task, assignee, status, action.
    expect(template).toContain('150px');
    expect(template).toContain('140px');
    expect(template).toContain('72px');
  });

  it('collapses the row to a single column on a phone', () => {
    setViewport(true);
    render(<InpatientSchedule {...baseProps} />);

    // One track, and none of the fixed widths that made the row 600px wide.
    expect(rowTemplate()).toBe('minmax(0, 1fr)');
    expect(rowTemplate()).not.toContain('150px');
  });

  it('still renders every control once stacked', () => {
    setViewport(true);
    render(<InpatientSchedule {...baseProps} />);

    /* The point of stacking rather than clipping: the action a phone user needs
       is present, not pushed off the side of the screen. */
    expect(screen.getByText('Post-op wound check')).toBeInTheDocument();
    expect(screen.getByLabelText('View Post-op wound check')).toBeInTheDocument();
  });
});
