import { Express } from "express";
import organizationRounter from "./organization.router";
import companionRouter from "./companion.router";
import parentRouter from "./parent.router";
import userOrganizationRouter from "./user-organization.router";
import userRouter from "./user.router";
import userProfileRouter from "./user-profile.router";
import availabilityRouter from "./availability.router";
import specialtyRouter from "./speciality.router";
import organisationRoomRouter from "./organisation-room.router";
import organisationInviteRouter from "./organisation-invite.router";
import authUserMobileRouter from "./authUserMobile.router";
import coParentInviteRouter from "./coparentInvite.router";
import parentCompanionRouter from "./parent-companion.router";
import companionOrganisationRouter from "./companion-organisation.router";
import docuemntRouter from "./document.router";
import serviceRouter from "./service.router";
import appointmentRouter from "./appointment.router";
import stripeRouter from "./stripe.router";
import financeRouter from "./finance.router";
import documensoRouter from "./documenso.router";
import ratingRouter from "./organisationRating.router";
import formRouter from "./form.router";
import formAssignmentRouter from "./form-assignment.router";
import templateRouter from "./template.router";
import templateFhirRouter from "./template.fhir.router";
import renderedDocumentFhirRouter from "./rendered-document.fhir.router";
import clinicalArtifactFhirRouter from "./clinical-artifact.fhir.router";
import prescriptionRouter from "./prescription.router";
import expenseRouter from "./expense.router";
import deviceTokenRouter from "./deviceToken.router";
import chatRouter from "./chat.router";
import notificationRouter from "./notification.router";
import contactRouter from "./contact-us.router";
import accountWithdrawalRouter from "./account-withdrawal.router";
import organisationDocumentRouter from "./organisation-document.router";
import adverseEventRouter from "./adverse-event.router";
import taskRouter from "./task.router";
import taskFhirRouter from "./task.fhir.router";
import taskScheduleFhirRouter from "./task-schedule.fhir.router";
import workspaceRouter from "./workspace.router";
import inventoryRoter from "./inventory.router";
import searchRouter from "./search.router";
import observationToolRouter from "./observationTool.routes";
import dashboardRouter from "./dashboard.router";
import mobileConfigRouter from "./mobile.config.router";
import auditTrailRouter from "./audit-trail.router";
import integrationRouter from "./integration.router";
import knowledgeRouter from "./knowledge.router";
import codeRouter from "./code.router";
import labOrderRouter from "./lab-order.router";
import labResultRouter from "./lab-result.router";
import companionHistoryRouter from "./companion-history.router";
import authRouter from "./auth.router";
import catalogRouter from "./catalog.router";
import healthcareServiceRouter from "./healthcare-service.router";
import episodeOfCareRouter from "./episode-of-care.router";
import encounterRouter from "./encounter.router";
import roomUnitRouter from "./room-unit.router";
import roomUnitGroupRouter from "./room-unit-group.router";
import companionCardRouter from "./companion-card.router";
import companionCardPublicRouter from "./companion-card-public.router";
import petPassportRouter from "./pet-passport.router";
import petPassportPublicRouter from "./pet-passport-public.router";
import treatmentProtocolRouter from "./treatment-protocol.router";
import waitlistRouter from "./waitlist.router";
import referralLetterRouter from "./referral-letter.router";
import insuranceClaimRouter from "./insurance-claim.router";
import careReminderRouter from "./care-reminder.router";
import patientProblemRouter from "./patient-problem.router";
import patientAllergyRouter from "./patient-allergy.router";
import vitalSignRouter from "./vital-sign.router";
import marRouter from "./mar.router";
import preventiveCarePlanRouter from "./preventive-care-plan.router";
import surgicalProcedureRouter from "./surgical-procedure.router";
import patientConsentRouter from "./patient-consent.router";
import dischargeInstructionRouter from "./discharge-instruction.router";
import diagnosticImageRouter from "./diagnostic-image.router";
import soapNoteRouter from "./soap-note.router";
import bloodTransfusionRouter from "./blood-transfusion.router";
import fluidTherapyPlanRouter from "./fluid-therapy-plan.router";
import nutritionPlanRouter from "./nutrition-plan.router";
import postOpCarePlanRouter from "./post-op-care-plan.router";
import anesthesiaRecordRouter from "./anesthesia-record.router";
import hospitalizationMonitoringRouter from "./hospitalization-monitoring.router";
import physiotherapyPlanRouter from "./physiotherapy-plan.router";
import woundAssessmentRouter from "./wound-assessment.router";
import pathologySubmissionRouter from "./pathology-submission.router";
import emergencyTriageRouter from "./emergency-triage.router";
import icuCarePlanRouter from "./icu-care-plan.router";
import painAssessmentRouter from "./pain-assessment.router";
import bodyConditionRouter from "./body-condition.router";
import medicationReconciliationRouter from "./medication-reconciliation.router";
import clinicalProgressNoteRouter from "./clinical-progress-note.router";
import dentalExaminationRouter from "./dental-examination.router";
import reproductiveRecordRouter from "./reproductive-record.router";
import ophthalmologyExaminationRouter from "./ophthalmology-examination.router";
import cardiologyAssessmentRouter from "./cardiology-assessment.router";
import behaviorAssessmentRouter from "./behavior-assessment.router";
import dermatologyAssessmentRouter from "./dermatology-assessment.router";
import neurologyAssessmentRouter from "./neurology-assessment.router";
import oncologyAssessmentRouter from "./oncology-assessment.router";
import nutritionAssessmentRouter from "./nutrition-assessment.router";
import pocLabRouter from "./poc-lab.router";
import geneticHealthScreenRouter from "./genetic-health-screen.router";
import qolAssessmentRouter from "./qol-assessment.router";
import controlledSubstanceLogRouter from "./controlled-substance-log.router";
import aftercarePlanRouter from "./aftercare-plan.router";
import bloodBankRouter from "./blood-bank.router";
import { estimateRouter } from "./estimate.router";
import { deceasedRecordRouter } from "./deceased-record.router";
import { admissionRouter } from "./admission.router";
import { surgicalChecklistRouter } from "./surgical-checklist.router";
import { drugFormularyRouter } from "./drug-formulary.router";
import { clientComplaintRouter } from "./client-complaint.router";
import { preOpAssessmentRouter } from "./pre-op-assessment.router";
import { isolationProtocolRouter } from "./isolation-protocol.router";
import { patientTransferRouter } from "./patient-transfer.router";
import { clinicEquipmentRouter } from "./clinic-equipment.router";
import { appointmentReminderLogRouter } from "./appointment-reminder-log.router";
import { waitlistEntryRouter } from "./waitlist-entry.router";
import { adverseEventReportRouter } from "./adverse-event-report.router";
import { bodyConditionRecordRouter } from "./body-condition-record.router";
import { qualityOfLifeAssessmentRouter } from "./quality-of-life-assessment.router";
import { clinicalAlertLogRouter } from "./clinical-alert-log.router";
import { telemedicineSessionRouter } from "./telemedicine-session.router";
import { patientCheckInRouter } from "./patient-check-in.router";
import { anaesthesiaRecordRouter } from "./anaesthesia-record.router";

export function registerRoutes(app: Express) {
  app.use(`/fhir/v1/organization`, organizationRounter);
  app.use(`/fhir/v1/companion`, companionRouter);
  app.use(`/fhir/v1/parent`, parentRouter);
  app.use(`/fhir/v1/user-organization`, userOrganizationRouter);
  app.use(`/fhir/v1/user`, userRouter);
  app.use(`/fhir/v1/user-profile`, userProfileRouter);
  app.use(`/fhir/v1/speciality`, specialtyRouter);
  app.use(`/fhir/v1/organisation-room`, organisationRoomRouter);
  app.use(`/fhir/v1/room-unit`, roomUnitRouter);
  app.use(`/fhir/v1/room-unit-group`, roomUnitGroupRouter);
  app.use(`/fhir/v1/organisation-invites`, organisationInviteRouter);
  app.use(`/fhir/v1/availability`, availabilityRouter);
  app.use(`/v1/authUser`, authUserMobileRouter);
  app.use(`/v1/coparent-invite`, coParentInviteRouter);
  app.use(`/v1/parent-companion`, parentCompanionRouter);
  app.use(`/v1/companion-organisation`, companionOrganisationRouter);
  app.use(`/v1/document`, docuemntRouter);
  app.use(`/fhir/v1/service`, serviceRouter);
  app.use(`/fhir/v1/healthcare-service`, healthcareServiceRouter);
  app.use(`/fhir/v1/appointment`, appointmentRouter);
  app.use(`/fhir/v1/episode-of-care`, episodeOfCareRouter);
  app.use(`/fhir/v1/encounter`, encounterRouter);
  app.use(`/v1/stripe`, stripeRouter);
  app.use(`/v1/finance`, financeRouter);
  app.use(`/v1/documenso`, documensoRouter);
  app.use(`/v1/organisation-rating`, ratingRouter);
  app.use(`/fhir/v1/invoice`, financeRouter);
  app.use(`/fhir/v1/form`, formRouter);
  app.use(`/v1/forms`, formAssignmentRouter);
  app.use(`/fhir/v1/template`, templateFhirRouter);
  app.use(`/fhir/v1/rendered-document`, renderedDocumentFhirRouter);
  app.use(`/fhir/v1/task`, taskFhirRouter);
  app.use(`/fhir/v1/clinical-artifact`, clinicalArtifactFhirRouter);
  app.use(`/fhir/v1/task-schedule`, taskScheduleFhirRouter);
  app.use(`/v1/templates`, templateRouter);
  app.use(`/v1/workspace`, workspaceRouter);
  app.use(`/v1/prescriptions`, prescriptionRouter);
  app.use(`/v1/search`, searchRouter);
  app.use(`/v1/expense`, expenseRouter);
  app.use(`/v1/device-token`, deviceTokenRouter);
  app.use(`/v1/chat`, chatRouter);
  app.use(`/v1/notification`, notificationRouter);
  app.use(`/v1/contact-us`, contactRouter);
  app.use(`/v1/account-withdrawal`, accountWithdrawalRouter);
  app.use(`/v1/organisation-document`, organisationDocumentRouter);
  app.use(`/v1/adverse-event`, adverseEventRouter);
  app.use(`/v1/task`, taskRouter);
  app.use(`/v1/inventory`, inventoryRoter);
  app.use(`/v1/observation-tools`, observationToolRouter);
  app.use(`/v1/dashboard`, dashboardRouter);
  app.use(`/v1/mobile-config`, mobileConfigRouter);
  app.use(`/v1/audit-trail`, auditTrailRouter);
  app.use(`/v1/companion-history`, companionHistoryRouter);
  app.use(`/v1/companion-card`, companionCardRouter);
  app.use(`/public/companion-card`, companionCardPublicRouter);
  app.use(`/v1/pet-passport`, petPassportRouter);
  app.use(`/public/pet-passport`, petPassportPublicRouter);
  app.use(`/v1`, treatmentProtocolRouter);
  app.use(`/v1`, waitlistRouter);
  app.use(`/v1`, referralLetterRouter);
  app.use(`/v1`, insuranceClaimRouter);
  app.use(`/v1`, careReminderRouter);
  app.use(`/v1`, patientProblemRouter);
  app.use(`/v1`, patientAllergyRouter);
  app.use(`/v1`, vitalSignRouter);
  app.use(`/v1`, marRouter);
  app.use(`/v1`, preventiveCarePlanRouter);
  app.use(`/v1`, surgicalProcedureRouter);
  app.use(`/v1`, patientConsentRouter);
  app.use(`/v1`, dischargeInstructionRouter);
  app.use(`/v1`, diagnosticImageRouter);
  app.use(`/v1`, soapNoteRouter);
  app.use(`/v1`, bloodTransfusionRouter);
  app.use(`/v1`, fluidTherapyPlanRouter);
  app.use(`/v1`, nutritionPlanRouter);
  app.use(`/v1`, postOpCarePlanRouter);
  app.use(`/v1`, anesthesiaRecordRouter);
  app.use(`/v1`, hospitalizationMonitoringRouter);
  app.use(`/v1`, physiotherapyPlanRouter);
  app.use(`/v1`, woundAssessmentRouter);
  app.use(`/v1`, pathologySubmissionRouter);
  app.use(`/v1`, emergencyTriageRouter);
  app.use(`/v1`, icuCarePlanRouter);
  app.use(`/v1`, painAssessmentRouter);
  app.use(`/v1`, bodyConditionRouter);
  app.use(`/v1`, medicationReconciliationRouter);
  app.use(`/v1`, clinicalProgressNoteRouter);
  app.use(`/v1`, dentalExaminationRouter);
  app.use(`/v1`, reproductiveRecordRouter);
  app.use(`/v1`, ophthalmologyExaminationRouter);
  app.use(`/v1`, cardiologyAssessmentRouter);
  app.use(`/v1`, behaviorAssessmentRouter);
  app.use(`/v1`, dermatologyAssessmentRouter);
  app.use(`/v1`, neurologyAssessmentRouter);
  app.use(`/v1`, oncologyAssessmentRouter);
  app.use(`/v1`, nutritionAssessmentRouter);
  app.use(`/v1`, pocLabRouter);
  app.use(`/v1`, geneticHealthScreenRouter);
  app.use(`/v1`, qolAssessmentRouter);
  app.use(`/v1`, controlledSubstanceLogRouter);
  app.use(`/v1`, aftercarePlanRouter);
  app.use(`/v1`, bloodBankRouter);
  app.use(`/v1`, estimateRouter);
  app.use(`/v1`, deceasedRecordRouter);
  app.use(`/v1`, admissionRouter);
  app.use(`/v1`, surgicalChecklistRouter);
  app.use(`/v1`, drugFormularyRouter);
  app.use(`/v1`, clientComplaintRouter);
  app.use(`/v1`, preOpAssessmentRouter);
  app.use(`/v1`, isolationProtocolRouter);
  app.use(`/v1`, patientTransferRouter);
  app.use(`/v1`, clinicEquipmentRouter);
  app.use(`/v1`, appointmentReminderLogRouter);
  app.use(`/v1`, waitlistEntryRouter);
  app.use(`/v1`, adverseEventReportRouter);
  app.use(`/v1`, bodyConditionRecordRouter);
  app.use(`/v1`, qualityOfLifeAssessmentRouter);
  app.use(`/v1`, clinicalAlertLogRouter);
  app.use(`/v1`, telemedicineSessionRouter);
  app.use(`/v1`, patientCheckInRouter);
  app.use(`/v1`, anaesthesiaRecordRouter);
  app.use(`/v1/integration`, integrationRouter);
  app.use(`/v1/knowledge`, knowledgeRouter);
  app.use(`/v1/codes`, codeRouter);
  app.use(`/v1/labs`, labOrderRouter);
  app.use(`/v1/labs`, labResultRouter);
  app.use(`/v1/auth`, authRouter);
  app.use(`/v1/catalog`, catalogRouter);
}
