import { CompanionRecord } from '@/app/features/documents/types/companionDocuments';
import {
  LIFECYCLE_TAB_ORDER,
  RECORD_LIFECYCLE_FILTERS,
  RECORD_LIFECYCLE_LABELS,
  deriveRecordLifecycle,
  filterRecordsByLifecycle,
  getAvailableLifecycleTabs,
  getLifecycleForFilter,
} from '@/app/features/documents/components/recordLifecycle';

const rec = (partial: Partial<CompanionRecord>): CompanionRecord => ({
  title: '',
  category: 'HEALTH',
  subcategory: 'OTHER',
  attachments: [],
  ...partial,
});

describe('recordLifecycle', () => {
  describe('deriveRecordLifecycle', () => {
    it('prefers an explicit lifecycle from the backend over every derived signal', () => {
      expect(
        deriveRecordLifecycle(
          rec({
            lifecycle: 'requested',
            signedAt: '2026-07-01T00:00:00Z',
            sourceKind: 'TEMPLATE_INSTANCE',
            uploadedByPmsUserId: 'user-1',
          })
        )
      ).toBe('requested');
    });

    it.each<CompanionRecord['lifecycle']>(['requested', 'uploaded', 'generated', 'signed'])(
      'passes the explicit %s lifecycle straight through',
      (lifecycle) => {
        expect(deriveRecordLifecycle(rec({ lifecycle }))).toBe(lifecycle);
      }
    );

    it('resolves signed from a signing timestamp', () => {
      expect(deriveRecordLifecycle(rec({ signedAt: '2026-07-01T00:00:00Z' }))).toBe('signed');
    });

    it('ranks a signing timestamp above a generated source kind', () => {
      expect(
        deriveRecordLifecycle(
          rec({ signedAt: '2026-07-01T00:00:00Z', sourceKind: 'CLINICAL_ARTIFACT' })
        )
      ).toBe('signed');
    });

    it('ignores a null signing timestamp', () => {
      expect(deriveRecordLifecycle(rec({ signedAt: null, uploadedByParentId: 'p1' }))).toBe(
        'uploaded'
      );
    });

    it('resolves generated from a non-document source kind', () => {
      expect(deriveRecordLifecycle(rec({ sourceKind: 'TEMPLATE_INSTANCE' }))).toBe('generated');
    });

    it('ranks a generated source kind above the uploader ids', () => {
      expect(
        deriveRecordLifecycle(rec({ sourceKind: 'CLINICAL_ARTIFACT', uploadedByPmsUserId: 'u1' }))
      ).toBe('generated');
    });

    it('does not treat a plain DOCUMENT source kind as generated', () => {
      expect(deriveRecordLifecycle(rec({ sourceKind: 'DOCUMENT' }))).toBeUndefined();
    });

    it('resolves uploaded when a pet parent uploaded the file', () => {
      expect(deriveRecordLifecycle(rec({ uploadedByParentId: 'parent-1' }))).toBe('uploaded');
    });

    it('resolves uploaded when a clinic user uploaded the file', () => {
      expect(deriveRecordLifecycle(rec({ uploadedByPmsUserId: 'user-1' }))).toBe('uploaded');
    });

    it('returns undefined when no lifecycle signal is present', () => {
      expect(deriveRecordLifecycle(rec({}))).toBeUndefined();
    });

    it('ignores null uploader ids', () => {
      expect(
        deriveRecordLifecycle(rec({ uploadedByParentId: null, uploadedByPmsUserId: null }))
      ).toBeUndefined();
    });

    // syncedFromPms is set by the backend to Boolean(pmsUserId) at create time,
    // so it means "created through the PMS", never "generated by the system".
    it('never infers generated from syncedFromPms alone', () => {
      expect(deriveRecordLifecycle(rec({ syncedFromPms: true }))).toBeUndefined();
    });

    // A staff upload carries syncedFromPms AND an uploader id; it is an upload.
    it('classifies a synced staff upload as uploaded, not generated', () => {
      expect(deriveRecordLifecycle(rec({ syncedFromPms: true, uploadedByPmsUserId: 'u1' }))).toBe(
        'uploaded'
      );
    });

    // The create endpoint rejects a document with no attachments, so an empty
    // array is not a "still awaiting the file" signal.
    it('never infers requested from an empty attachment list', () => {
      expect(deriveRecordLifecycle(rec({ attachments: [] }))).toBeUndefined();
    });

    // signingStatus is pmsVisible-derived on this endpoint and always 'SIGNED'.
    it('never infers signed from pmsVisible', () => {
      expect(deriveRecordLifecycle(rec({ pmsVisible: true }))).toBeUndefined();
    });
  });

  describe('getLifecycleForFilter', () => {
    it.each([
      ['LIFECYCLE_REQUESTED', 'requested'],
      ['LIFECYCLE_UPLOADED', 'uploaded'],
      ['LIFECYCLE_GENERATED', 'generated'],
      ['LIFECYCLE_SIGNED', 'signed'],
    ])('maps %s to the %s lifecycle', (filter, lifecycle) => {
      expect(getLifecycleForFilter(filter)).toBe(lifecycle);
    });

    it.each(['ALL', 'UPLOADED', 'SYNCED'])(
      'returns undefined for the %s source filter',
      (filter) => {
        expect(getLifecycleForFilter(filter)).toBeUndefined();
      }
    );
  });

  describe('RECORD_LIFECYCLE_LABELS / FILTERS', () => {
    it('labels every lifecycle with the design wording', () => {
      expect(RECORD_LIFECYCLE_LABELS).toEqual({
        requested: 'Requested',
        uploaded: 'Uploaded',
        generated: 'Generated',
        signed: 'Signed',
      });
    });

    it('namespaces every lifecycle filter value', () => {
      expect(Object.values(RECORD_LIFECYCLE_FILTERS)).toEqual([
        'LIFECYCLE_REQUESTED',
        'LIFECYCLE_UPLOADED',
        'LIFECYCLE_GENERATED',
        'LIFECYCLE_SIGNED',
      ]);
    });
  });

  describe('LIFECYCLE_TAB_ORDER', () => {
    // `uploaded` is deliberately absent: the source-based "Uploaded" pill
    // already owns that label in the tab row.
    it('omits uploaded so the label is not duplicated', () => {
      expect(LIFECYCLE_TAB_ORDER).toEqual(['requested', 'generated', 'signed']);
    });
  });

  describe('getAvailableLifecycleTabs', () => {
    it('returns nothing for records that carry no lifecycle signal', () => {
      expect(getAvailableLifecycleTabs([rec({}), rec({ syncedFromPms: true })])).toEqual([]);
    });

    it('omits uploaded even when records resolve to it', () => {
      expect(getAvailableLifecycleTabs([rec({ uploadedByParentId: 'p1' })])).toEqual([]);
    });

    it('surfaces only the lifecycles present, in design order', () => {
      const tabs = getAvailableLifecycleTabs([
        rec({ signedAt: '2026-07-01T00:00:00Z' }),
        rec({ lifecycle: 'requested' }),
        rec({ uploadedByPmsUserId: 'u1' }),
      ]);
      expect(tabs).toEqual(['requested', 'signed']);
    });

    it('deduplicates repeated lifecycles', () => {
      const tabs = getAvailableLifecycleTabs([
        rec({ sourceKind: 'TEMPLATE_INSTANCE' }),
        rec({ sourceKind: 'CLINICAL_ARTIFACT' }),
      ]);
      expect(tabs).toEqual(['generated']);
    });

    it('handles an empty record list', () => {
      expect(getAvailableLifecycleTabs([])).toEqual([]);
    });
  });

  describe('filterRecordsByLifecycle', () => {
    const requested = rec({ id: 'r1', lifecycle: 'requested' });
    const generated = rec({ id: 'g1', sourceKind: 'TEMPLATE_INSTANCE' });
    const signed = rec({ id: 's1', signedAt: '2026-07-01T00:00:00Z' });
    const uploaded = rec({ id: 'u1', uploadedByParentId: 'p1' });
    const unknown = rec({ id: 'x1' });
    const all = [requested, generated, signed, uploaded, unknown];

    it.each([
      ['requested', requested],
      ['generated', generated],
      ['signed', signed],
      ['uploaded', uploaded],
    ] as const)('keeps only the %s records', (lifecycle, expected) => {
      expect(filterRecordsByLifecycle(all, lifecycle)).toEqual([expected]);
    });

    it('excludes records with no lifecycle from every bucket', () => {
      expect(filterRecordsByLifecycle(all, 'requested')).not.toContain(unknown);
    });
  });
});
