import {
  CompanionRecord,
  RecordLifecycle,
} from '@/app/features/documents/types/companionDocuments';

/** Filter value for a lifecycle tab, namespaced so it cannot collide with the
 * source filters ('ALL' / 'UPLOADED' / 'SYNCED') in `RecordFilter`. */
export type RecordLifecycleFilter =
  'LIFECYCLE_REQUESTED' | 'LIFECYCLE_UPLOADED' | 'LIFECYCLE_GENERATED' | 'LIFECYCLE_SIGNED';

/**
 * Maps a record to the design's lifecycle tabs ("Requested / Uploaded /
 * Generated / Signed") using only signals the companion documents API really
 * carries.
 *
 * Precedence, most specific first:
 *  1. `lifecycle`  — an explicit lifecycle from the backend always wins.
 *  2. `signedAt`   — a genuine signing timestamp.
 *  3. `sourceKind` — anything other than a plain uploaded 'DOCUMENT' was
 *                    produced by the system (a rendered template instance or
 *                    clinical artifact), i.e. generated.
 *  4. uploader ids — a human (pet parent or clinic staff) put the file there.
 *
 * Only arm 4 resolves from data that ships today; arms 1–3 depend on fields the
 * endpoint does not populate yet, so their tabs stay hidden until it does (see
 * `getAvailableLifecycleTabs`). There is deliberately no "requested" derivation:
 * nothing in the current payload distinguishes a record awaiting its file.
 *
 * Explicitly NOT used as signals, because each would fabricate a state:
 *  - `syncedFromPms` means "created through the PMS by a staff user" (the
 *    backend sets it to `Boolean(pmsUserId)` at create time), not "generated by
 *    the system". Mapping it to `generated` would relabel every staff upload.
 *  - `attachments.length === 0` is not "awaiting a file": the create endpoint
 *    rejects a document with no attachments, and the only rows that legitimately
 *    carry an empty array are rendered (generated) documents.
 *  - the DTO's `signingStatus` is, on this endpoint, `pmsVisible ? 'SIGNED' :
 *    'NOT_STARTED'` over a list already filtered to `pmsVisible: true`, so it is
 *    the constant 'SIGNED' and carries no signing information.
 */
export const deriveRecordLifecycle = (record: CompanionRecord): RecordLifecycle | undefined => {
  if (record.lifecycle) return record.lifecycle;
  if (record.signedAt) return 'signed';
  if (record.sourceKind && record.sourceKind !== 'DOCUMENT') return 'generated';
  if (record.uploadedByParentId || record.uploadedByPmsUserId) return 'uploaded';
  return undefined;
};

export const RECORD_LIFECYCLE_LABELS: Record<RecordLifecycle, string> = {
  requested: 'Requested',
  uploaded: 'Uploaded',
  generated: 'Generated',
  signed: 'Signed',
};

export const RECORD_LIFECYCLE_FILTERS: Record<RecordLifecycle, RecordLifecycleFilter> = {
  requested: 'LIFECYCLE_REQUESTED',
  uploaded: 'LIFECYCLE_UPLOADED',
  generated: 'LIFECYCLE_GENERATED',
  signed: 'LIFECYCLE_SIGNED',
};

const LIFECYCLE_BY_FILTER = new Map<RecordLifecycleFilter, RecordLifecycle>(
  (Object.keys(RECORD_LIFECYCLE_LABELS) as RecordLifecycle[]).map((lifecycle) => [
    RECORD_LIFECYCLE_FILTERS[lifecycle],
    lifecycle,
  ])
);

/** The lifecycle a filter value selects, or `undefined` for a source filter. */
export const getLifecycleForFilter = (filter: string): RecordLifecycle | undefined =>
  LIFECYCLE_BY_FILTER.get(filter as RecordLifecycleFilter);

/**
 * Tab order from the design, minus `uploaded`. The record list already ships a
 * source-based "Uploaded" pill (records not created through the PMS), and a
 * second pill with the same label but a different meaning would be ambiguous —
 * so the lifecycle `uploaded` arm stays available to `deriveRecordLifecycle`
 * without claiming its own tab.
 */
export const LIFECYCLE_TAB_ORDER: RecordLifecycle[] = ['requested', 'generated', 'signed'];

/**
 * The lifecycle tabs worth rendering: one per lifecycle that at least one loaded
 * record actually resolves to. Keeps permanently-empty tabs off screen while the
 * backing fields are unpopulated.
 */
export const getAvailableLifecycleTabs = (records: CompanionRecord[]): RecordLifecycle[] => {
  const present = new Set<RecordLifecycle>();
  for (const record of records) {
    const lifecycle = deriveRecordLifecycle(record);
    if (lifecycle) present.add(lifecycle);
  }
  return LIFECYCLE_TAB_ORDER.filter((lifecycle) => present.has(lifecycle));
};

export const filterRecordsByLifecycle = (
  records: CompanionRecord[],
  lifecycle: RecordLifecycle
): CompanionRecord[] => records.filter((record) => deriveRecordLifecycle(record) === lifecycle);
