/**
 * Complete theme mock for tests
 * Import this in test files to ensure consistent and complete theme mocking
 * This matches the actual theme structure from src/theme/
 */

export const createMockTheme = () => ({
  spacing: {
    '0': 0,
    '1': 4,
    '1.25': 5,
    '2': 8,
    '2.5': 10,
    '3': 12,
    '3.5': 14,
    '4': 16,
    '4.5': 18,
    '5': 20,
    '6': 24,
    '7': 28,
    '8': 32,
    '9': 36,
    '10': 40,
    '11': 44,
    '12': 48,
    '14': 56,
    '16': 64,
    '18': 72,
    '20': 80,
    '24': 96,
    '28': 112,
    '30': 120,
    '32': 128,
    '36': 144,
    '40': 160,
    '44': 176,
    '48': 192,
    '52': 208,
    '56': 224,
    '60': 240,
    '64': 256,
    '72': 288,
    '80': 320,
    '96': 384,
  },
  borderRadius: {
    none: 0,
    xs: 16,
    sm: 16,
    base: 16,
    md: 16,
    lg: 16,
    xl: 16,
    '2xl': 16,
    '3xl': 16,
    full: 9999,
    field: 16,
    cardSmall: 18,
    card: 20,
    button: 18,
    sheet: 28,
    screen: 28,
    chip: 9999,
    pill: 9999,
  },
  shadows: {
    none: {
      shadowColor: 'transparent',
      shadowOffset: {width: 0, height: 0},
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    xs: {
      shadowColor: '#000000',
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    sm: {
      shadowColor: '#000000',
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    base: {
      shadowColor: '#000000',
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    md: {
      shadowColor: '#000000',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000000',
      shadowOffset: {width: 0, height: 10},
      shadowOpacity: 0.15,
      shadowRadius: 15,
      elevation: 8,
    },
    xl: {
      shadowColor: '#000000',
      shadowOffset: {width: 0, height: 20},
      shadowOpacity: 0.25,
      shadowRadius: 25,
      elevation: 12,
    },
    card: {
      boxShadow:
        '0px 1px 2px rgba(29,28,27,0.03), 0px 8px 22px rgba(29,28,27,0.05)',
    },
    screen: {
      boxShadow:
        '0px 2px 6px rgba(29,28,27,0.05), 0px 28px 70px rgba(29,28,27,0.10)',
    },
    cta: {boxShadow: '0px 8px 22px rgba(29,28,27,0.16)'},
    companion: {boxShadow: '0px 4px 14px rgba(244,121,190,0.12)'},
    glassPill: {
      boxShadow:
        '0px 2px 4px rgba(29,28,27,0.05), 0px 12px 28px rgba(29,28,27,0.10)',
    },
  },
  typography: {
    h1: {
      fontSize: 36,
      fontWeight: '700',
      lineHeight: 45,
      fontFamily: 'ClashDisplay-Bold',
    },
    h2: {
      fontSize: 30,
      fontWeight: '700',
      lineHeight: 37.5,
      fontFamily: 'ClashDisplay-Bold',
    },
    h3: {
      fontSize: 26,
      fontWeight: '500',
      lineHeight: 31.2,
      fontFamily: 'ClashGrotesk-Medium',
      letterSpacing: -0.26,
    },
    h4: {
      fontSize: 20,
      fontWeight: '600',
      lineHeight: 27.5,
      fontFamily: 'ClashDisplay-Semibold',
    },
    h5: {
      fontSize: 18,
      fontWeight: '500',
      lineHeight: 27,
      fontFamily: 'ClashDisplay-Medium',
    },
    h6: {
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 24,
      fontFamily: 'ClashDisplay-Medium',
    },
    headlineLarge: {fontSize: 32, fontWeight: '700'},
    headlineMedium: {fontSize: 28, fontWeight: '600'},
    headlineSmall: {fontSize: 24, fontWeight: '600'},
    titleLarge: {
      fontSize: 20,
      fontWeight: '500',
      lineHeight: 24,
      fontFamily: 'ClashGrotesk-Medium',
      letterSpacing: -0.2,
    },
    titleMedium: {
      fontSize: 18,
      fontWeight: '500',
      lineHeight: 21.6,
      fontFamily: 'ClashGrotesk-Medium',
      letterSpacing: -0.18,
    },
    titleSmall: {
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 19.2,
      fontFamily: 'ClashGrotesk-Medium',
      letterSpacing: -0.16,
    },
    bodyLarge: {
      fontSize: 18,
      fontWeight: '400',
      lineHeight: 29.25,
      fontFamily: 'Satoshi-Regular',
    },
    bodyMedium: {
      fontSize: 14,
      fontWeight: '400',
      fontFamily: 'Satoshi-Regular',
    },
    bodySmall: {
      fontSize: 14,
      fontWeight: '400',
      lineHeight: 21,
      fontFamily: 'Satoshi-Regular',
    },
    bodySmallTight: {
      fontSize: 14,
      fontWeight: '400',
      lineHeight: 19.6,
      fontFamily: 'Satoshi-Regular',
    },
    bodyExtraSmall: {
      fontSize: 13,
      fontWeight: '400',
      lineHeight: 16,
      fontFamily: 'Satoshi-Regular',
    },
    labelLarge: {fontSize: 14, fontWeight: '500'},
    labelMedium: {fontSize: 12, fontWeight: '500'},
    labelSmall: {
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 21,
      fontFamily: 'Satoshi-Medium',
    },
    labelXsBold: {
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 15.6,
      fontFamily: 'Satoshi-Bold',
      letterSpacing: 0,
    },
    labelXxsBold: {
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 14.4,
      fontFamily: 'Satoshi-Bold',
      letterSpacing: 0,
    },
    button: {
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 20,
      fontFamily: 'Satoshi-Medium',
    },
    buttonSmall: {
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 14,
      fontFamily: 'Satoshi-Medium',
    },
    caption: {
      fontSize: 12,
      fontWeight: '400',
      lineHeight: 18,
      fontFamily: 'SFProText-regular',
    },
    captionBold: {
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 18,
      fontFamily: 'SFProText-semibold',
    },
    paragraph: {
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 19.2,
      fontFamily: 'Satoshi-Regular',
      letterSpacing: -0.32,
    },
    paragraphBold: {
      fontSize: 16,
      fontWeight: '700',
      lineHeight: 19.2,
      fontFamily: 'Satoshi-Bold',
      letterSpacing: -0.32,
    },
    cta: {
      fontSize: 18,
      fontWeight: '500',
      lineHeight: 18,
      fontFamily: 'ClashGrotesk-Medium',
      letterSpacing: -0.18,
    },
    screenTitle: {
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 19.2,
      fontFamily: 'ClashGrotesk-Medium',
      letterSpacing: -0.16,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 16,
      fontFamily: 'Satoshi-Bold',
      letterSpacing: -0.42,
    },
    input: {
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 19.2,
      fontFamily: 'Satoshi-Regular',
      letterSpacing: -0.32,
    },
    inputFilled: {
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 16,
      fontFamily: 'Satoshi-Medium',
      letterSpacing: -0.48,
    },
    inputError: {
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 16,
      fontFamily: 'Satoshi-Bold',
      letterSpacing: -0.42,
      color: '#EA3729',
    },
    tabLabelFocused: {
      fontSize: 12,
      fontWeight: '900',
      lineHeight: 14.4,
      fontFamily: 'Satoshi-Black',
    },
    tabLabel: {
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 14.4,
      fontFamily: 'Satoshi-Medium',
    },
    h4Alt: {
      fontSize: 23,
      fontWeight: '500',
      lineHeight: 27.6,
      fontFamily: 'ClashGrotesk-Medium',
      letterSpacing: -0.23,
    },
    h5Clash23: {
      fontSize: 23,
      fontWeight: '500',
      lineHeight: 27.6,
      fontFamily: 'ClashGrotesk-Medium',
      letterSpacing: -0.46,
    },
    paragraph18Bold: {
      fontSize: 18,
      fontWeight: '700',
      lineHeight: 21.6,
      fontFamily: 'Satoshi-Bold',
      letterSpacing: -0.36,
    },
    subtitleBold14: {
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 16.8,
      fontFamily: 'Satoshi-Bold',
      opacity: 0.6,
    },
    buttonH6Clash19: {
      fontSize: 19,
      fontWeight: '500',
      lineHeight: 22.8,
      fontFamily: 'ClashGrotesk-Medium',
      letterSpacing: -0.38,
    },
    body: {
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 24,
      fontFamily: 'Satoshi-Regular',
    },
    label: {
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 24,
      fontFamily: 'Satoshi-Medium',
    },
    labelSmallBold: {
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 21,
      fontFamily: 'Satoshi-Bold',
    },
    labelXs: {
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 18,
      fontFamily: 'Satoshi-Medium',
    },
    buttonLarge: {
      fontSize: 19,
      fontWeight: '500',
      lineHeight: 22.8,
      fontFamily: 'ClashGrotesk-Medium',
      letterSpacing: -0.38,
    },
    h6Clash: {
      fontSize: 18,
      fontWeight: '500',
      lineHeight: 21.6,
      fontFamily: 'ClashGrotesk-Medium',
      letterSpacing: -0.18,
    },
    subtitleBold12: {
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 14.4,
      fontFamily: 'Satoshi-Bold',
    },
    body12: {
      fontSize: 12,
      fontWeight: '400',
      lineHeight: 15.6,
      fontFamily: 'Satoshi-Regular',
    },
    clashBody13: {
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 15.6,
      fontFamily: 'ClashGrotesk-Medium',
      letterSpacing: -0.13,
    },
    pillSubtitleBold15: {
      fontSize: 15,
      fontWeight: '700',
      lineHeight: 24,
      fontFamily: 'Satoshi-Bold',
      letterSpacing: -0.3,
    },
    businessSectionTitle20: {
      fontSize: 20,
      fontWeight: '500',
      lineHeight: 24,
      fontFamily: 'ClashGrotesk-Medium',
      letterSpacing: -0.2,
    },
    businessTitle16: {
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 19.2,
      fontFamily: 'ClashGrotesk-Medium',
      letterSpacing: -0.16,
    },
    subtitleRegular14: {
      fontSize: 14,
      fontWeight: '400',
      lineHeight: 16.8,
      fontFamily: 'Satoshi-Regular',
    },
    captionBoldSatoshi: {
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 15.6,
      fontFamily: 'Satoshi-Bold',
      letterSpacing: 0,
    },
    labelMdBold: {
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 21,
      fontFamily: 'Satoshi-Bold',
    },
    // Additional font size properties
    '2xl': {fontSize: 24, lineHeight: 24},
    '3xl': {fontSize: 30, lineHeight: 30},
    '4xl': {fontSize: 36, lineHeight: 36},
    // Mobile-specific + warm-bone serif display (mirror src/theme/typography.ts)
    mobileBodyEmphasis: {
      fontSize: 17,
      fontWeight: '500',
      lineHeight: 22,
      fontFamily: 'Satoshi-Medium',
      letterSpacing: 0,
    },
    mobileFootnote: {
      fontSize: 13,
      fontWeight: '400',
      lineHeight: 20,
      fontFamily: 'Satoshi-Regular',
      letterSpacing: 0,
    },
    sectionHeading: {
      fontSize: 17,
      fontWeight: '700',
      lineHeight: 22,
      fontFamily: 'Satoshi-Bold',
      letterSpacing: 0,
    },
    serifTitle: {
      fontSize: 30,
      fontWeight: '400',
      lineHeight: 34,
      fontFamily: 'Newsreader-Regular',
      letterSpacing: -0.45,
    },
    serifTitleSmall: {
      fontSize: 28,
      fontWeight: '400',
      lineHeight: 33,
      fontFamily: 'Newsreader-Regular',
      letterSpacing: -0.42,
    },
    greeting: {
      fontSize: 17,
      fontWeight: '400',
      lineHeight: 22,
      fontFamily: 'Newsreader-Italic',
      fontStyle: 'italic',
      letterSpacing: -0.17,
    },
    emptyStateTitle: {
      fontSize: 24,
      fontWeight: '400',
      lineHeight: 29,
      fontFamily: 'Newsreader-Regular',
      letterSpacing: -0.36,
    },
    amountHero: {
      fontSize: 34,
      fontWeight: '400',
      lineHeight: 38,
      fontFamily: 'Newsreader-Regular',
      letterSpacing: -0.5,
    },
    onboardingHeadline: {
      fontSize: 34,
      fontWeight: '400',
      lineHeight: 40,
      fontFamily: 'Newsreader-Regular',
      letterSpacing: -0.5,
    },
    eyebrow: {
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 15,
      fontFamily: 'Satoshi-Bold',
      letterSpacing: 1.44,
      textTransform: 'uppercase',
    },
  },
  colors: {
    // Matches the actual theme colors from src/theme/colors.ts
    primary: '#257BED',
    primaryDark: '#E55A2B',
    primaryLight: '#FF8A65',
    primaryGlass: 'rgba(36, 122, 237, 0.92)',
    primaryTint: 'rgba(36, 122, 237, 0.2)',
    primaryTintStrong: 'rgba(36, 122, 237, 0.8)',
    primarySurface: 'rgba(36, 122, 237, 0.08)',
    secondary: '#302F2E',
    accent: '#FFE066',
    background: '#FFFEFE',
    backgroundSecondary: '#F8F9FA',
    cardBackground: '#FFFFFF',
    surface: '#FFFFFF',
    text: '#302F2E',
    textSecondary: '#747473',
    textTertiary: '#257BED',
    onPrimary: '#FEF8F4',
    border: '#EAEAEA',
    borderMuted: 'rgba(234, 234, 234, 0.9)',
    borderSeparator: '#c8c8c8ff',
    placeholder: '#595958',
    cardOverlay: 'rgba(255, 255, 255, 0.95)',
    success: '#008F5D',
    successLight: '#E6F4EF',
    warning: '#FF9800',
    error: '#F44336',
    errorSurface: '#FDEBEA',
    info: '#2196F3',
    transparent: 'transparent',
    overlay: 'rgba(0, 0, 0, 0.5)',
    whiteOverlay70: 'rgba(255, 255, 255, 0.7)',
    white: '#FFFFFF',
    black: '#000000',
    gray800: '#424242',
    lightBlueBackground: '#E9F2FD',
    inputBackground: '#FBF8F2',
    neutralShadow: 'rgba(71, 56, 39, 0.15)',
    // Warm-bone tokens (additive; mirror src/theme/colors.ts light values).
    page: '#EFE8DC',
    band: '#E8E0D2',
    inset: '#EAE2D5',
    screen: '#F7F3EC',
    screen2: '#F1EBE1',
    fieldBg: '#FBF8F2',
    hairline: '#E5DCCF',
    hairlineHover: '#D6D1CD',
    divider: '#D6D1CD',
    ink: '#1D1C1B',
    inkBody: '#302F2E',
    inkSoft: '#423F3C',
    inkMuted: '#5C5956',
    inkFaint: '#8F8984',
    inkFaint2: '#A9A39E',
    cta: '#302F2E',
    ctaHover: '#1D1C1B',
    ctaText: '#FFFFFF',
    spot: '#1D1C1B',
    blue: '#257BED',
    blueText: '#257BED',
    blueSoft: '#E6F2FF',
    navActive: '#1657C9',
    navActiveBg: 'rgba(37, 123, 237, 0.11)',
    pink: '#FF90D4',
    pinkGlow: 'rgba(244, 121, 190, 0.12)',
    cyan: '#5CE1E6',
    cyanText: '#38CCD8',
    danger: '#EA3729',
    dangerText: '#EA3729',
    dangerSurface: '#FDEBEA',
    indigo: '#4F46E5',
    indigoSurface: '#E0E7FF',
    violet: '#7C3AED',
    violetSurface: '#EDE9FE',
    successSurface: 'rgba(0, 143, 93, 0.12)',
    warningSurface: 'rgba(255, 152, 0, 0.12)',
    avatarAmberBg: '#FEF3E9',
    avatarAmberInk: '#AF5E19',
    avatarVioletBg: '#F5F3FF',
    avatarVioletInk: '#5B21B6',
    avatarGreenBg: '#E6F4EF',
    avatarGreenInk: '#006642',
    glassPill: 'rgba(239, 232, 220, 0.93)',
    glassPillBorder: 'rgba(29, 28, 27, 0.09)',
    glassSurface: 'rgba(247, 243, 236, 0.55)',
    glassSurfaceStrong: 'rgba(247, 243, 236, 0.72)',
  },
});

export const mockTheme = createMockTheme();

export const createMockUseTheme = (overrides = {}) => ({
  theme: {...mockTheme, ...overrides},
  isDark: false,
  themeMode: 'light' as const,
  darkModeLocked: true,
  setTheme: jest.fn(),
  toggleTheme: jest.fn(),
});
