import type { Meta, StoryObj } from '@storybook/react';
import { expect, fn, userEvent, within } from 'storybook/test';
import type { TemplateLike } from '@yosemite-crew/types';

import type { ScheduleTask } from '@/app/features/appointments/types/workspace';
import InpatientSchedule from './InpatientSchedule';

/**
 * Tasks with no `startDate` are always in the day window, so the fixture renders
 * the same rows whatever day the story is opened on.
 */
const TASKS: ScheduleTask[] = [
  {
    id: 'task-obs',
    time: '08:00',
    description: 'Post-op wound check',
    subtext: 'Photograph the site and log any discharge',
    category: 'Care',
    assignedToId: 'staff-priya',
    assignedToName: 'Priya Raman',
    status: 'UPCOMING',
    autoGenerated: false,
  },
  {
    id: 'task-meds',
    time: '10:00',
    description: 'Meloxicam 1.5 mg/ml - 0.4 ml PO',
    subtext: 'With food; skip if not eating and flag the lead',
    category: 'Medication',
    assignedToId: 'staff-halloran',
    assignedToName: 'Nurse Halloran',
    status: 'PENDING',
    autoGenerated: true,
    sourceRefId: 'rx-1180',
  },
  {
    id: 'task-fluids',
    time: '12:30',
    description: 'IV fluids - recalculate rate',
    category: 'Treatment',
    assignedToId: 'staff-ravi',
    assignedToName: 'Dr. Ravi Menon',
    status: 'COMPLETED',
    autoGenerated: false,
  },
  {
    id: 'task-call',
    time: '16:00',
    description: 'Call owner with the evening update',
    category: 'Communication',
    assignedToId: 'staff-tom',
    assignedToName: 'Tom Beckett',
    status: 'CANCELLED',
    autoGenerated: false,
  },
];

const ASSIGNEES = [
  { label: 'Priya Raman', value: 'staff-priya' },
  { label: 'Nurse Halloran', value: 'staff-halloran' },
  { label: 'Dr. Ravi Menon', value: 'staff-ravi' },
  { label: 'Tom Beckett', value: 'staff-tom' },
];

const LONG_ASSIGNEES = [
  { label: 'Dr. Alexandra Featherstonehaugh', value: 'staff-alex' },
  { label: 'Priya Raman', value: 'staff-priya' },
];

/**
 * Only `id` and `name` are read - the search matches on the name and the append
 * handler is given the id - so the fixture is cast rather than filled with the
 * twenty ownership/version fields the contract carries.
 */
const template = (id: string, name: string): TemplateLike =>
  ({ id, name }) as unknown as TemplateLike;

const TEMPLATES: TemplateLike[] = [
  template('tpl-postop', 'Post-op recovery bundle'),
  template('tpl-postop-ortho', 'Post-op orthopaedic bundle'),
  template('tpl-dental', 'Dental day-patient bundle'),
];

/** Reads the authored track list off an element that sets it inline. */
const tracks = (element: Element | null | undefined): string =>
  (element as HTMLElement | null)?.style.gridTemplateColumns ?? '';

const meta = {
  title: 'Workspace/InpatientSchedule',
  component: InpatientSchedule,
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        component:
          'The inpatient day schedule: a timeline gutter, one flat row per task, and three ' +
          'surfaces that exist only after an interaction. None of the three had ever been drawn.\n\n' +
          '**The column tracks are the reason this file matters most.** The header and every row ' +
          'set `gridTemplateColumns` from an inline style string built at render time - ' +
          '`96px 20px 150px minmax(0, 1fr) {n}ch 140px 72px` for the header and the last five of ' +
          'those for the row - where `{n}` is computed from the longest assignee label, clamped ' +
          'between 14ch and 20ch. Two failure modes live there and neither is visible to tsc, ' +
          'eslint or jest: a malformed track list (a comma between tracks, say) makes the browser ' +
          'drop the whole declaration and collapse the row into one column, and the header and row ' +
          'strings can drift out of step so the labels stop sitting over their columns. The play ' +
          'functions read both strings back off the DOM and assert the header ends with the row.\n\n' +
          '**The status popover** is a `role="menu"` under the pill, with a coloured dot per ' +
          "option taken from `getStatusStyle`. It closes on the trigger's `onBlur`, so the " +
          'options commit on `onMouseDown` with `preventDefault` - a click that dispatched on ' +
          '`onClick` would arrive after the menu had already gone. A `COMPLETED` task is final ' +
          'and renders a static pill with no caret instead.\n\n' +
          '**The search box doubles as a template finder**: a query that matches a published ' +
          'template name opens a "Task templates" panel below the field, capped at five ' +
          "suggestions, whose rows append the template's blocks to the schedule.\n\n" +
          "**Each row's assignee control** is a `LabelDropdown`, whose listbox portals to " +
          '`document.body` - outside `canvasElement` entirely, which is part of why it was never ' +
          'snapshotted.\n\n' +
          'Note the header row is `hidden lg:grid`, so it only paints at 1024px and up; below that ' +
          'the rows carry no labels at all.',
      },
    },
  },
  tags: ['autodocs'],
  args: {
    tasks: TASKS,
    templates: TEMPLATES,
    readOnly: false,
    assigneeOptions: ASSIGNEES,
    onAddTask: fn(),
    onViewTask: fn(),
    onAssignTask: fn(),
    onStatusChange: fn(),
    onAppendTemplate: fn(),
  },
} satisfies Meta<typeof InpatientSchedule>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: 'Day schedule',
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    // The header labels hang off the same inline track list as the rows, so
    // assert the two strings agree rather than trusting the source.
    const header = canvas.getByText('Timeline').parentElement;
    const row = canvas.getByText('Post-op wound check').closest('[style]');
    // An invalid track list is dropped whole by the browser and reads back as
    // '' - the exact shape of the popover bug this sweep exists for.
    await expect(tracks(header)).not.toBe('');
    await expect(tracks(row)).not.toBe('');
    // 'Nurse Halloran' and 'Dr. Ravi Menon' are 14 characters, so the assignee
    // track resolves to 16ch and both strings must carry the same value.
    await expect(tracks(header).endsWith(tracks(row))).toBe(true);
    await expect(tracks(row)).toContain('16ch');
  },
  parameters: {
    docs: {
      story:
        'Four tasks across one day. The completed row is the only one whose status pill is static; ' +
        'the cancelled row drops its timeline marker to the neutral ring.',
    },
  },
};

export const StatusMenuOpen: Story = {
  name: 'Status menu open',
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    // Every changeable row has a trigger named "Status"; take the first.
    await userEvent.click(canvas.getAllByRole('button', { name: 'Status' })[0]);
    const menu = canvas.getByRole('menu');
    // Assert the menu has its OPTIONS and its dots. "the trigger flipped
    // aria-expanded" passes on an empty panel.
    await expect(within(menu).getAllByRole('menuitem')).toHaveLength(4);
    await expect(within(menu).getByRole('menuitem', { name: 'Cancelled' })).toBeInTheDocument();
    await expect(menu.querySelectorAll('span[style*="background-color"]')).toHaveLength(4);
  },
  parameters: {
    docs: {
      story:
        'The four transitions, each with the 8px dot in its own status colour and the label in the ' +
        'matching ink. The panel is `w-full` against the pill, so it is as narrow as the trigger ' +
        'rather than as wide as "Cancelled" - worth seeing at every viewport.',
    },
  },
};

export const StatusChanged: Story = {
  name: 'Status picked',
  play: async ({ canvasElement, args }) => {
    const canvas = within(canvasElement);
    await userEvent.click(canvas.getAllByRole('button', { name: 'Status' })[0]);
    await userEvent.click(canvas.getByRole('menuitem', { name: 'Cancelled' }));
    await expect(args.onStatusChange).toHaveBeenCalledWith('task-obs', 'CANCELLED');
    await expect(canvas.queryByRole('menu')).not.toBeInTheDocument();
  },
  parameters: {
    docs: {
      story:
        'Picking commits and closes. This is the story that guards the `onMouseDown` + ' +
        '`preventDefault` ordering: on `onClick` the trigger would blur first, the menu would ' +
        'unmount, and the option would never fire.',
    },
  },
};

export const TemplateSuggestions: Story = {
  name: 'Template suggestions open',
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    await userEvent.type(canvas.getByLabelText('Search tasks, assignees or templates'), 'post-op');
    const caption = canvas.getByText('Task templates');
    const panel = caption.parentElement as HTMLElement;
    // Two of the three templates match, so assert the panel drew BOTH rows -
    // and the caption alone would not have proved that.
    await expect(
      within(panel).getByRole('button', { name: /Post-op recovery bundle/ })
    ).toBeVisible();
    await expect(
      within(panel).getByRole('button', { name: /Post-op orthopaedic bundle/ })
    ).toBeVisible();
    await expect(within(panel).getAllByRole('button')).toHaveLength(2);
  },
  parameters: {
    docs: {
      story:
        'The same query filters the rows and searches published templates, so this frame shows ' +
        'both at once: one matching task left in the list, and the suggestion panel over it. The ' +
        'panel is capped at five entries.',
    },
  },
};

export const TemplateAppended: Story = {
  name: 'Template picked',
  play: async ({ canvasElement, args }) => {
    const canvas = within(canvasElement);
    await userEvent.type(canvas.getByLabelText('Search tasks, assignees or templates'), 'dental');
    await userEvent.click(canvas.getByRole('button', { name: /Dental day-patient bundle/ }));
    await expect(args.onAppendTemplate).toHaveBeenCalledWith('tpl-dental');
    // Picking clears the query, which both closes the panel and restores the
    // full day - the row list must come back with it.
    await expect(canvas.queryByText('Task templates')).not.toBeInTheDocument();
    await expect(canvas.getByText('Post-op wound check')).toBeInTheDocument();
  },
  parameters: {
    docs: {
      story:
        'Appending resets the search, so the schedule returns to the whole day in the same tick ' +
        'the panel disappears.',
    },
  },
};

export const AssigneeDropdownOpen: Story = {
  name: 'Assignee listbox open',
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    await userEvent.click(canvas.getByRole('button', { name: 'Assigned to: Priya Raman' }));
    // The listbox portals to document.body, so it is outside canvasElement.
    const panel = document.querySelector('[data-portal-dropdown]') as HTMLElement | null;
    await expect(panel).toBeInTheDocument();
    const options = within(panel as HTMLElement).getAllByRole('button');
    await expect(options).toHaveLength(4);
    await expect(options[0]).toHaveTextContent('Priya Raman');
    await expect(options.at(-1)).toHaveTextContent('Tom Beckett');
  },
  parameters: {
    docs: {
      story:
        'Reassigning a task inline. The panel is `searchable={false}` here, so it is a plain list ' +
        'with the current owner marked on the `--nav-active-bg` wash - and being portalled, it ' +
        'escapes the row it belongs to and can overlap the row below.',
    },
  },
};

export const LongAssigneeNames: Story = {
  name: 'Long assignee names (20ch clamp)',
  args: {
    assigneeOptions: LONG_ASSIGNEES,
    tasks: TASKS.map((task) =>
      task.id === 'task-obs'
        ? { ...task, assignedToId: 'staff-alex', assignedToName: 'Dr. Alexandra Featherstonehaugh' }
        : task
    ),
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const header = canvas.getByText('Timeline').parentElement;
    const row = canvas.getByText('Post-op wound check').closest('[style]');
    // 30 characters + 2 would be 32ch; the clamp holds the column at 20ch and
    // the label truncates instead of widening the grid.
    await expect(tracks(row)).toContain('20ch');
    await expect(tracks(header).endsWith(tracks(row))).toBe(true);
  },
  parameters: {
    docs: {
      story:
        'The assignee column is sized from the longest option, so a 30-character name would ' +
        'otherwise eat the task column. `clamp(len + 2, 14, 20)` pins it at 20ch and the trigger ' +
        'truncates - the only frame where the header/row track strings are anything but 16ch.',
    },
  },
};

export const ReadOnly: Story = {
  name: 'Read-only',
  args: { readOnly: true },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    // Read-only disables adding, but the status pill and the assignee dropdown
    // stay live - worth pinning, since it looks like a locked panel and is not.
    await expect(canvas.getByRole('button', { name: 'Add schedule task' })).toBeDisabled();
    await expect(canvas.getAllByRole('button', { name: 'Status' })[0]).toBeEnabled();
  },
  parameters: {
    docs: {
      story:
        'What a discharged or cancelled visit shows. Only the add affordance is disabled; the ' +
        'inline controls are not, which is a discrepancy this frame makes visible.',
    },
  },
};

export const NoTasks: Story = {
  name: 'Empty day',
  args: { tasks: [] },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    await expect(canvas.getByText('No schedule tasks for this day.')).toBeInTheDocument();
    // The header only renders alongside rows, so an empty day has no labels.
    await expect(canvas.queryByText('Timeline')).not.toBeInTheDocument();
  },
  parameters: {
    docs: {
      story:
        'With nothing scheduled the column header is dropped as well as the rows, so the empty ' +
        'notice sits directly under the toolbar rather than under a set of orphaned labels.',
    },
  },
};

export const NoSearchMatch: Story = {
  name: 'Search matches nothing',
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    await userEvent.type(
      canvas.getByLabelText('Search tasks, assignees or templates'),
      'radiology'
    );
    await expect(canvas.getByText('No schedule tasks match this search.')).toBeInTheDocument();
    await expect(canvas.queryByText('Task templates')).not.toBeInTheDocument();
  },
  parameters: {
    docs: {
      story:
        'A query that matches neither a task nor a template. The empty copy changes wording ' +
        'between "for this day" and "match this search" - two strings only one of which any ' +
        'snapshot had.',
    },
  },
};
