-- Adds the AuditEventType values that reached schema.prisma without a matching
-- migration. Postgres enums are not derived from the Prisma schema at runtime,
-- so audit() calls using these labels fail with
--   invalid input value for enum "AuditEventType"
-- against any database migrated from the committed history.
--
-- Each value is inserted at its schema position with BEFORE rather than
-- appended: `migrate diff` compares enum ORDER, so a plain ADD VALUE leaves the
-- database ordered differently from schema.prisma and the drift check then asks
-- for a full enum rewrite of the AuditTrail.eventType column.
--
-- IF NOT EXISTS keeps this idempotent where a `prisma db push` already
-- introduced some of the values out-of-band.

ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'HOSPITALIZATION_OBS_RECORDED' BEFORE 'WOUND_ASSESSMENT_RECORDED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PHYSIOTHERAPY_PLAN_CREATED' BEFORE 'WOUND_ASSESSMENT_RECORDED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PHYSIOTHERAPY_PLAN_UPDATED' BEFORE 'WOUND_ASSESSMENT_RECORDED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PHYSIOTHERAPY_PLAN_DISCONTINUED' BEFORE 'WOUND_ASSESSMENT_RECORDED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'CONSENT_FORM_SIGNED' BEFORE 'EQUIPMENT_MAINTENANCE_LOGGED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'ADVERSE_EVENT_REPORTED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'CLINICAL_ALERT_TRIGGERED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'CLINICAL_ALERT_ACKNOWLEDGED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'TELEMEDICINE_SESSION_STARTED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'TELEMEDICINE_SESSION_COMPLETED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PRESCRIPTION_CREATED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PRESCRIPTION_SIGNED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PRESCRIPTION_VOIDED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PRESCRIPTION_DISPENSE_REQUESTED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PRESCRIPTION_DISPENSED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PRESCRIPTION_DISPENSE_REJECTED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'DISCHARGE_SUMMARY_CREATED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'DISCHARGE_SUMMARY_UPDATED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PATIENT_CHECKED_IN' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PATIENT_SEEN' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'ANAESTHESIA_STARTED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'ANAESTHESIA_COMPLETED' BEFORE 'STAFF_SHIFT_SCHEDULED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'ANAESTHESIA_ABORTED' BEFORE 'STAFF_SHIFT_SCHEDULED';
