-- Adds the AuditEventType values that reached schema.prisma without a matching
-- migration. Postgres enums are not derived from the Prisma schema at runtime, so
-- audit() calls using these labels fail with
--   invalid input value for enum "AuditEventType"
-- against any database migrated from the committed history.
--
-- IF NOT EXISTS keeps this idempotent for environments where an earlier
-- `prisma db push` already introduced some of the values out-of-band.

ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'HOSPITALIZATION_OBS_RECORDED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PHYSIOTHERAPY_PLAN_CREATED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PHYSIOTHERAPY_PLAN_UPDATED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PHYSIOTHERAPY_PLAN_DISCONTINUED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'CONSENT_FORM_SIGNED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'ADVERSE_EVENT_REPORTED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'CLINICAL_ALERT_TRIGGERED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'CLINICAL_ALERT_ACKNOWLEDGED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'TELEMEDICINE_SESSION_STARTED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'TELEMEDICINE_SESSION_COMPLETED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PRESCRIPTION_CREATED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PRESCRIPTION_SIGNED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PRESCRIPTION_VOIDED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PRESCRIPTION_DISPENSE_REQUESTED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PRESCRIPTION_DISPENSED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PRESCRIPTION_DISPENSE_REJECTED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'DISCHARGE_SUMMARY_CREATED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'DISCHARGE_SUMMARY_UPDATED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PATIENT_CHECKED_IN';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PATIENT_SEEN';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'ANAESTHESIA_STARTED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'ANAESTHESIA_COMPLETED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'ANAESTHESIA_ABORTED';
