ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'EXAM_RECORDED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PASSPORT_CONSENT_REQUESTED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PASSPORT_CONSENT_GRANTED';
ALTER TYPE "AuditEventType" ADD VALUE IF NOT EXISTS 'PASSPORT_CONSENT_REVOKED';
