import { Schema, model, HydratedDocument } from "mongoose";

export type AuditActorType = "PMS_USER" | "PARENT" | "SYSTEM";

export type AuditEntityType =
  | "PATIENT_ORGANISATION"
  | "APPOINTMENT"
  | "ENCOUNTER"
  | "INVOICE"
  | "DOCUMENT"
  | "FORM"
  | "TASK"
  | "PARENT"
  | "COMPANION";

export type AuditEventType =
  | "PATIENT_ORG_LINK_CREATED"
  | "PATIENT_ORG_LINK_REQUESTED"
  | "PATIENT_ORG_LINK_APPROVED"
  | "PATIENT_ORG_LINK_REJECTED"
  | "PATIENT_ORG_LINK_REVOKED"
  | "PATIENT_ORG_INVITE_ACCEPTED"
  | "PATIENT_ORG_INVITE_REJECTED"
  | "PATIENT_ORG_LINK_AUTO"
  | "APPOINTMENT_REQUESTED"
  | "APPOINTMENT_CREATED"
  | "APPOINTMENT_APPROVED"
  | "APPOINTMENT_CANCELLED"
  | "APPOINTMENT_RESCHEDULED"
  | "APPOINTMENT_CHECKED_IN"
  | "ENCOUNTER_DISCHARGE_OVERRIDDEN"
  | "ENCOUNTER_DISCHARGED"
  | "INVOICE_CREATED"
  | "INVOICE_UPDATED"
  | "INVOICE_PAID"
  | "INVOICE_FAILED"
  | "INVOICE_REFUNDED"
  | "INVOICE_CANCELLED"
  | "DOCUMENT_ADDED"
  | "DOCUMENT_UPDATED"
  | "DOCUMENT_DELETED"
  | "FORM_ATTACHED"
  | "FORM_SUBMITTED"
  | "TASK_CREATED"
  | "TASK_REASSIGNED"
  | "TASK_STATUS_CHANGED"
  | "PARENT_ALERT_CREATED"
  | "PARENT_ALERT_UPDATED"
  | "PARENT_ALERT_DELETED"
  | "COMPANION_ALERT_CREATED"
  | "COMPANION_ALERT_UPDATED"
  | "COMPANION_ALERT_DELETED"
  | "COMPANION_CARD_SHARE_ISSUED"
  | "COMPANION_CARD_VIEWED"
  | "COMPANION_CARD_SHARE_REVOKED"
  | "VACCINATION_RECORDED"
  | "TREATMENT_RECORDED"
  | "TITRATION_RECORDED"
  | "EXAM_RECORDED"
  | "PASSPORT_ISSUED"
  | "PASSPORT_CONSENT_REQUESTED"
  | "PASSPORT_CONSENT_GRANTED"
  | "PASSPORT_CONSENT_REVOKED"
  | "PROTOCOL_APPLIED"
  | "WAITLIST_ENTRY_ADDED"
  | "WAITLIST_ENTRY_OFFERED"
  | "WAITLIST_ENTRY_BOOKED"
  | "WAITLIST_ENTRY_CANCELLED"
  | "WAITLIST_ENTRY_EXPIRED"
  | "REFERRAL_LETTER_CREATED"
  | "REFERRAL_LETTER_SIGNED"
  | "REFERRAL_LETTER_SENT"
  | "REFERRAL_LETTER_CANCELLED"
  | "INSURANCE_CLAIM_CREATED"
  | "INSURANCE_CLAIM_SUBMITTED"
  | "INSURANCE_CLAIM_STATUS_CHANGED"
  | "INSURANCE_CLAIM_CANCELLED"
  | "CARE_REMINDER_SENT"
  | "CARE_REMINDER_RESPONDED"
  | "CARE_REMINDER_CANCELLED"
  | "PROBLEM_CREATED"
  | "PROBLEM_UPDATED"
  | "PROBLEM_RESOLVED"
  | "ALLERGY_RECORDED"
  | "ALLERGY_UPDATED"
  | "ALLERGY_RESOLVED"
  | "VITAL_SIGNS_RECORDED"
  | "VITAL_SIGNS_UPDATED"
  | "MAR_ENTRY_CREATED"
  | "MAR_ENTRY_ADMINISTERED"
  | "MAR_ENTRY_HELD"
  | "MAR_ENTRY_MISSED"
  | "CARE_PLAN_CREATED"
  | "CARE_PLAN_UPDATED"
  | "CARE_PLAN_CANCELLED"
  | "CARE_PLAN_ITEM_COMPLETED"
  | "SURGERY_RECORDED"
  | "SURGERY_OUTCOME_UPDATED"
  | "CONSENT_GRANTED"
  | "CONSENT_REVOKED"
  | "DISCHARGE_INSTRUCTIONS_CREATED"
  | "DISCHARGE_INSTRUCTIONS_SENT"
  | "DISCHARGE_INSTRUCTIONS_ACKNOWLEDGED"
  | "DIAGNOSTIC_IMAGE_RECORDED"
  | "DIAGNOSTIC_IMAGE_REVIEWED"
  | "SOAP_NOTE_CREATED"
  | "SOAP_NOTE_SIGNED"
  | "SOAP_NOTE_AMENDED"
  | "TRANSFUSION_RECORDED"
  | "TRANSFUSION_REACTION_REPORTED"
  | "FLUID_PLAN_CREATED"
  | "FLUID_PLAN_UPDATED"
  | "FLUID_PLAN_DISCONTINUED"
  | "NUTRITION_PLAN_CREATED"
  | "NUTRITION_PLAN_UPDATED"
  | "NUTRITION_PLAN_DISCONTINUED"
  | "POST_OP_PLAN_CREATED"
  | "POST_OP_PLAN_REVIEWED"
  | "POST_OP_PLAN_COMPLETED"
  | "ANESTHESIA_RECORD_CREATED"
  | "ANESTHESIA_RECORD_UPDATED"
  | "ANESTHESIA_RECORD_COMPLETED"
  | "HOSPITALIZATION_OBS_RECORDED"
  | "PHYSIOTHERAPY_PLAN_CREATED"
  | "PHYSIOTHERAPY_PLAN_UPDATED"
  | "PHYSIOTHERAPY_PLAN_DISCONTINUED"
  | "WOUND_ASSESSMENT_RECORDED"
  | "PATHOLOGY_SUBMITTED"
  | "PATHOLOGY_RESULTS_RECORDED"
  | "PATHOLOGY_REVIEWED"
  | "EMERGENCY_TRIAGE_RECORDED"
  | "EMERGENCY_TRIAGE_ESCALATED"
  | "ICU_CARE_PLAN_CREATED"
  | "ICU_CARE_PLAN_UPDATED"
  | "ICU_CARE_PLAN_DISCHARGED"
  | "PAIN_ASSESSMENT_RECORDED"
  | "BODY_CONDITION_RECORDED"
  | "MEDICATION_RECONCILIATION_STARTED"
  | "MEDICATION_RECONCILIATION_COMPLETED"
  | "MEDICATION_RECONCILIATION_REVIEWED"
  | "CLINICAL_NOTE_CREATED"
  | "CLINICAL_NOTE_SIGNED"
  | "DENTAL_EXAMINATION_RECORDED"
  | "REPRODUCTIVE_RECORD_CREATED"
  | "REPRODUCTIVE_RECORD_UPDATED"
  | "OPHTHALMOLOGY_EXAMINATION_RECORDED"
  | "CARDIOLOGY_ASSESSMENT_RECORDED"
  | "BEHAVIOR_ASSESSMENT_RECORDED"
  | "DERMATOLOGY_ASSESSMENT_RECORDED"
  | "NEUROLOGY_ASSESSMENT_RECORDED"
  | "ONCOLOGY_ASSESSMENT_RECORDED"
  | "NUTRITION_ASSESSMENT_RECORDED"
  | "POC_LAB_RECORDED"
  | "GENETIC_SCREEN_RECORDED"
  | "QOL_ASSESSMENT_RECORDED"
  | "CONTROLLED_SUBSTANCE_LOGGED"
  | "AFTERCARE_PLAN_RECORDED"
  | "BLOOD_DONOR_REGISTERED"
  | "BLOOD_DONATION_COLLECTED"
  | "ESTIMATE_CREATED"
  | "ESTIMATE_APPROVED"
  | "ESTIMATE_DECLINED"
  | "DECEASED_RECORD_CREATED"
  | "ADMISSION_CREATED"
  | "ADMISSION_DISCHARGED";

export interface AuditTrailMongo {
  organisationId: string;
  patientId: string;
  eventType: AuditEventType;

  actorType?: AuditActorType;
  actorId?: string | null;
  actorName?: string | null;

  entityType?: AuditEntityType;
  entityId?: string | null;

  metadata?: Record<string, unknown>;
  occurredAt: Date;
  createdAt?: Date;
  updatedAt?: Date;
}

const AuditTrailSchema = new Schema(
  {
    organisationId: { type: String, required: true, index: true },
    patientId: { type: String, required: true, index: true },
    eventType: { type: String, required: true, index: true },

    actorType: {
      type: String,
      enum: ["PMS_USER", "PARENT", "SYSTEM"],
      default: null,
    },
    actorId: { type: String, default: null },
    actorName: { type: String, default: null },

    entityType: {
      type: String,
      enum: [
        "PATIENT_ORGANISATION",
        "APPOINTMENT",
        "ENCOUNTER",
        "INVOICE",
        "DOCUMENT",
        "FORM",
        "TASK",
        "PARENT",
        "COMPANION",
      ],
      default: null,
    },
    entityId: { type: String, default: null },

    metadata: { type: Schema.Types.Mixed, default: null },
    occurredAt: { type: Date, default: Date.now, index: true },
  },
  { timestamps: true },
);

AuditTrailSchema.index({ organisationId: 1, patientId: 1, occurredAt: -1 });
AuditTrailSchema.index({ organisationId: 1, occurredAt: -1 });

export type AuditTrailDocument = HydratedDocument<AuditTrailMongo>;

const AuditTrailModel = model<AuditTrailMongo>("AuditTrail", AuditTrailSchema);

export default AuditTrailModel;
