export {
  clinicalArtifactFhirMapper,
  type ClinicalArtifactKind,
  type ClinicalArtifactStatus,
  type ClinicalArtifactBaseInput,
  type SoapNoteInput,
  type SoapNoteRecord,
  type PrescriptionInput,
  type PrescriptionRecord,
  type DischargeSummaryInput,
  type DischargeSummaryRecord,
  type VitalRecordInput,
  type VitalRecordRecord,
  type ImmunizationRecord,
  type RabiesTitrationRecord,
  type ParasiteTreatmentRecord,
  type ClinicalExaminationRecord,
  type ClinicalArtifactRecordLike,
  type ClinicalArtifactFhirInputDefaults,
} from "@yosemite-crew/types";
