import { getIntegrationAdapter } from "src/integrations";
import { IdexxAdapter } from "src/integrations/idexx/idexx.adapter";
import { MerckAdapter } from "src/integrations/merck/merck.adapter";
import { LaikaAdapter } from "src/integrations/laika/laika.adapter";
import { VetnoxAdapter } from "src/integrations/vetnox/vetnox.adapter";
import { ClinicalKeyAdapter } from "src/integrations/clinical-key/clinical-key.adapter";
import { DrugInteractionCheckerAdapter } from "src/integrations/drug-interaction-checker/drug-interaction-checker.adapter";
import { DosageCalculatorAdapter } from "src/integrations/dosage-calculator/dosage-calculator.adapter";
import { ProtocolLibraryAdapter } from "src/integrations/protocol-library/protocol-library.adapter";
import { VetnioAdapter } from "src/integrations/vetnio/vetnio.adapter";
import { TalkatoAdapter } from "src/integrations/talkato/talkato.adapter";
import { ScribeVetAdapter } from "src/integrations/scribe-vet/scribe-vet.adapter";
import { DischargeBuilderAdapter } from "src/integrations/discharge-builder/discharge-builder.adapter";
import { TemplateEngineAdapter } from "src/integrations/template-engine/template-engine.adapter";
import { VoiceCommandsAdapter } from "src/integrations/voice-commands/voice-commands.adapter";
import { DigitalIntakeAdapter } from "src/integrations/digital-intake/digital-intake.adapter";
import { PatientMonitorAdapter } from "src/integrations/patient-monitor/patient-monitor.adapter";
import { FollowupAutomationAdapter } from "src/integrations/followup-automation/followup-automation.adapter";
import { CarePlanManagerAdapter } from "src/integrations/care-plan-manager/care-plan-manager.adapter";
import { WellnessTrackerAdapter } from "src/integrations/wellness-tracker/wellness-tracker.adapter";
import { BehaviorLoggerAdapter } from "src/integrations/behavior-logger/behavior-logger.adapter";
import { WebsiteBuilderAdapter } from "src/integrations/website-builder/website-builder.adapter";
import { ClientPortalAdapter } from "src/integrations/client-portal/client-portal.adapter";
import { OnlineBookingAdapter } from "src/integrations/online-booking/online-booking.adapter";
import { PetProfileAdapter } from "src/integrations/pet-profile/pet-profile.adapter";
import { TelehealthPortalAdapter } from "src/integrations/telehealth-portal/telehealth-portal.adapter";
import { ReviewManagerAdapter } from "src/integrations/review-manager/review-manager.adapter";
import { SmsAutomationAdapter } from "src/integrations/sms-automation/sms-automation.adapter";
import { EmailCampaignsAdapter } from "src/integrations/email-campaigns/email-campaigns.adapter";
import { AppointmentRemindersAdapter } from "src/integrations/appointment-reminders/appointment-reminders.adapter";
import { ClientMessagingAdapter } from "src/integrations/client-messaging/client-messaging.adapter";
import { CallIntegrationAdapter } from "src/integrations/call-integration/call-integration.adapter";
import { WhatsAppBusinessAdapter } from "src/integrations/whatsapp-business/whatsapp-business.adapter";
import { QuickBooksAdapter } from "src/integrations/quickbooks/quickbooks.adapter";
import { XeroAdapter } from "src/integrations/xero/xero.adapter";
import { InventorySyncAdapter } from "src/integrations/inventory-sync/inventory-sync.adapter";
import { PayrollProviderAdapter } from "src/integrations/payroll-provider/payroll-provider.adapter";
import { ExpenseTrackerAdapter } from "src/integrations/expense-tracker/expense-tracker.adapter";
import { BillingAutomationAdapter } from "src/integrations/billing-automation/billing-automation.adapter";
import { RadAnalyzerAdapter } from "src/integrations/rad-analyzer/rad-analyzer.adapter";
import { AntechAdapter } from "src/integrations/antech/antech.adapter";
import { HeskaAdapter } from "src/integrations/heska/heska.adapter";
import { VetScanAdapter } from "src/integrations/vetscan/vetscan.adapter";
import { MonitorSyncAdapter } from "src/integrations/monitor-sync/monitor-sync.adapter";
import { BusinessIntelligenceAdapter } from "src/integrations/business-intelligence/business-intelligence.adapter";
import { BenchmarkingAdapter } from "src/integrations/benchmarking/benchmarking.adapter";
import { DataExportAdapter } from "src/integrations/data-export/data-export.adapter";
import { RevenueAnalyticsAdapter } from "src/integrations/revenue-analytics/revenue-analytics.adapter";
import { ClinicalAnalyticsAdapter } from "src/integrations/clinical-analytics/clinical-analytics.adapter";
import { ComplianceReporterAdapter } from "src/integrations/compliance-reporter/compliance-reporter.adapter";
import { PlumbVeterinaryAdapter } from "src/integrations/plumb-veterinary/plumb-veterinary.adapter";
import { FormBuilderAdapter } from "src/integrations/form-builder/form-builder.adapter";
import { TemplateManagerAdapter } from "src/integrations/template-manager/template-manager.adapter";
import { ConfigSyncAdapter } from "src/integrations/config-sync/config-sync.adapter";
import { ProtocolSyncAdapter } from "src/integrations/protocol-sync/protocol-sync.adapter";
import { PharmacyIntegrationAdapter } from "src/integrations/pharmacy-integration/pharmacy-integration.adapter";
import { PetInsuranceAdapter } from "src/integrations/pet-insurance/pet-insurance.adapter";
import { ReferralNetworkAdapter } from "src/integrations/referral-network/referral-network.adapter";
import { LoyaltyProgramAdapter } from "src/integrations/loyalty-program/loyalty-program.adapter";
import { ECommerceAdapter } from "src/integrations/e-commerce/e-commerce.adapter";
import { SupplyChainAdapter } from "src/integrations/supply-chain/supply-chain.adapter";

describe("integrations index", () => {
  it("returns adapters for known providers", () => {
    const idexx = getIntegrationAdapter("IDEXX");
    const merck = getIntegrationAdapter("MERCK_MANUALS");
    const laika = getIntegrationAdapter("LAIKA");
    const vetnox = getIntegrationAdapter("VETNOX");
    const clinicalKey = getIntegrationAdapter("CLINICAL_KEY");
    const drugInteractionChecker = getIntegrationAdapter(
      "DRUG_INTERACTION_CHECKER",
    );
    const dosageCalculator = getIntegrationAdapter("DOSAGE_CALCULATOR");
    const protocolLibrary = getIntegrationAdapter("PROTOCOL_LIBRARY");
    const vetnio = getIntegrationAdapter("VETNIO");
    const talkato = getIntegrationAdapter("TALKATO");
    const scribeVet = getIntegrationAdapter("SCRIBE_VET");
    const dischargeBuilder = getIntegrationAdapter("DISCHARGE_BUILDER");
    const templateEngine = getIntegrationAdapter("TEMPLATE_ENGINE");
    const voiceCommands = getIntegrationAdapter("VOICE_COMMANDS");
    const digitalIntake = getIntegrationAdapter("DIGITAL_INTAKE");
    const patientMonitor = getIntegrationAdapter("PATIENT_MONITOR");
    const followupAutomation = getIntegrationAdapter("FOLLOWUP_AUTOMATION");
    const carePlanManager = getIntegrationAdapter("CARE_PLAN_MANAGER");
    const wellnessTracker = getIntegrationAdapter("WELLNESS_TRACKER");
    const behaviorLogger = getIntegrationAdapter("BEHAVIOR_LOGGER");
    const websiteBuilder = getIntegrationAdapter("WEBSITE_BUILDER");
    const clientPortal = getIntegrationAdapter("CLIENT_PORTAL");
    const onlineBooking = getIntegrationAdapter("ONLINE_BOOKING");
    const petProfile = getIntegrationAdapter("PET_PROFILE");
    const telehealthPortal = getIntegrationAdapter("TELEHEALTH_PORTAL");
    const reviewManager = getIntegrationAdapter("REVIEW_MANAGER");
    const smsAutomation = getIntegrationAdapter("SMS_AUTOMATION");
    const emailCampaigns = getIntegrationAdapter("EMAIL_CAMPAIGNS");
    const appointmentReminders = getIntegrationAdapter("APPOINTMENT_REMINDERS");
    const clientMessaging = getIntegrationAdapter("CLIENT_MESSAGING");
    const callIntegration = getIntegrationAdapter("CALL_INTEGRATION");
    const whatsappBusiness = getIntegrationAdapter("WHATSAPP_BUSINESS");
    const quickbooks = getIntegrationAdapter("QUICKBOOKS");
    const xero = getIntegrationAdapter("XERO");
    const inventorySync = getIntegrationAdapter("INVENTORY_SYNC");
    const payrollProvider = getIntegrationAdapter("PAYROLL_PROVIDER");
    const expenseTracker = getIntegrationAdapter("EXPENSE_TRACKER");
    const billingAutomation = getIntegrationAdapter("BILLING_AUTOMATION");
    const radAnalyzer = getIntegrationAdapter("RAD_ANALYZER");
    const antech = getIntegrationAdapter("ANTECH");
    const heska = getIntegrationAdapter("HESKA");
    const vetscan = getIntegrationAdapter("VETSCAN");
    const monitorSync = getIntegrationAdapter("MONITOR_SYNC");
    const businessIntelligence = getIntegrationAdapter("BUSINESS_INTELLIGENCE");
    const benchmarking = getIntegrationAdapter("BENCHMARKING");
    const dataExport = getIntegrationAdapter("DATA_EXPORT");
    const revenueAnalytics = getIntegrationAdapter("REVENUE_ANALYTICS");
    const clinicalAnalytics = getIntegrationAdapter("CLINICAL_ANALYTICS");
    const complianceReporter = getIntegrationAdapter("COMPLIANCE_REPORTER");
    const plumbVeterinary = getIntegrationAdapter("PLUMB_VETERINARY");
    const formBuilder = getIntegrationAdapter("FORM_BUILDER");
    const templateManager = getIntegrationAdapter("TEMPLATE_MANAGER");
    const configSync = getIntegrationAdapter("CONFIG_SYNC");
    const protocolSync = getIntegrationAdapter("PROTOCOL_SYNC");
    const pharmacyIntegration = getIntegrationAdapter("PHARMACY_INTEGRATION");
    const petInsurance = getIntegrationAdapter("PET_INSURANCE");
    const referralNetwork = getIntegrationAdapter("REFERRAL_NETWORK");
    const loyaltyProgram = getIntegrationAdapter("LOYALTY_PROGRAM");
    const eCommerce = getIntegrationAdapter("E_COMMERCE");
    const supplyChain = getIntegrationAdapter("SUPPLY_CHAIN");

    expect(idexx).toBeInstanceOf(IdexxAdapter);
    expect(merck).toBeInstanceOf(MerckAdapter);
    expect(laika).toBeInstanceOf(LaikaAdapter);
    expect(vetnox).toBeInstanceOf(VetnoxAdapter);
    expect(clinicalKey).toBeInstanceOf(ClinicalKeyAdapter);
    expect(drugInteractionChecker).toBeInstanceOf(
      DrugInteractionCheckerAdapter,
    );
    expect(dosageCalculator).toBeInstanceOf(DosageCalculatorAdapter);
    expect(protocolLibrary).toBeInstanceOf(ProtocolLibraryAdapter);
    expect(vetnio).toBeInstanceOf(VetnioAdapter);
    expect(talkato).toBeInstanceOf(TalkatoAdapter);
    expect(scribeVet).toBeInstanceOf(ScribeVetAdapter);
    expect(dischargeBuilder).toBeInstanceOf(DischargeBuilderAdapter);
    expect(templateEngine).toBeInstanceOf(TemplateEngineAdapter);
    expect(voiceCommands).toBeInstanceOf(VoiceCommandsAdapter);
    expect(digitalIntake).toBeInstanceOf(DigitalIntakeAdapter);
    expect(patientMonitor).toBeInstanceOf(PatientMonitorAdapter);
    expect(followupAutomation).toBeInstanceOf(FollowupAutomationAdapter);
    expect(carePlanManager).toBeInstanceOf(CarePlanManagerAdapter);
    expect(wellnessTracker).toBeInstanceOf(WellnessTrackerAdapter);
    expect(behaviorLogger).toBeInstanceOf(BehaviorLoggerAdapter);
    expect(websiteBuilder).toBeInstanceOf(WebsiteBuilderAdapter);
    expect(clientPortal).toBeInstanceOf(ClientPortalAdapter);
    expect(onlineBooking).toBeInstanceOf(OnlineBookingAdapter);
    expect(petProfile).toBeInstanceOf(PetProfileAdapter);
    expect(telehealthPortal).toBeInstanceOf(TelehealthPortalAdapter);
    expect(reviewManager).toBeInstanceOf(ReviewManagerAdapter);
    expect(smsAutomation).toBeInstanceOf(SmsAutomationAdapter);
    expect(emailCampaigns).toBeInstanceOf(EmailCampaignsAdapter);
    expect(appointmentReminders).toBeInstanceOf(AppointmentRemindersAdapter);
    expect(clientMessaging).toBeInstanceOf(ClientMessagingAdapter);
    expect(callIntegration).toBeInstanceOf(CallIntegrationAdapter);
    expect(whatsappBusiness).toBeInstanceOf(WhatsAppBusinessAdapter);
    expect(quickbooks).toBeInstanceOf(QuickBooksAdapter);
    expect(xero).toBeInstanceOf(XeroAdapter);
    expect(inventorySync).toBeInstanceOf(InventorySyncAdapter);
    expect(payrollProvider).toBeInstanceOf(PayrollProviderAdapter);
    expect(expenseTracker).toBeInstanceOf(ExpenseTrackerAdapter);
    expect(billingAutomation).toBeInstanceOf(BillingAutomationAdapter);
    expect(radAnalyzer).toBeInstanceOf(RadAnalyzerAdapter);
    expect(antech).toBeInstanceOf(AntechAdapter);
    expect(heska).toBeInstanceOf(HeskaAdapter);
    expect(vetscan).toBeInstanceOf(VetScanAdapter);
    expect(monitorSync).toBeInstanceOf(MonitorSyncAdapter);
    expect(businessIntelligence).toBeInstanceOf(BusinessIntelligenceAdapter);
    expect(benchmarking).toBeInstanceOf(BenchmarkingAdapter);
    expect(dataExport).toBeInstanceOf(DataExportAdapter);
    expect(revenueAnalytics).toBeInstanceOf(RevenueAnalyticsAdapter);
    expect(clinicalAnalytics).toBeInstanceOf(ClinicalAnalyticsAdapter);
    expect(complianceReporter).toBeInstanceOf(ComplianceReporterAdapter);
    expect(plumbVeterinary).toBeInstanceOf(PlumbVeterinaryAdapter);
    expect(formBuilder).toBeInstanceOf(FormBuilderAdapter);
    expect(templateManager).toBeInstanceOf(TemplateManagerAdapter);
    expect(configSync).toBeInstanceOf(ConfigSyncAdapter);
    expect(protocolSync).toBeInstanceOf(ProtocolSyncAdapter);
    expect(pharmacyIntegration).toBeInstanceOf(PharmacyIntegrationAdapter);
    expect(petInsurance).toBeInstanceOf(PetInsuranceAdapter);
    expect(referralNetwork).toBeInstanceOf(ReferralNetworkAdapter);
    expect(loyaltyProgram).toBeInstanceOf(LoyaltyProgramAdapter);
    expect(eCommerce).toBeInstanceOf(ECommerceAdapter);
    expect(supplyChain).toBeInstanceOf(SupplyChainAdapter);
  });
});
