name: CD API

on:
    push:
        branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Add Jobs for Linting & Testing & Deploy to AWS
jobs:
    changed-files-check:
      uses: ./.github/workflows/changed-files.yaml
      with:
        files: |
          package.json
          apps/api/**
    build-release:
        needs: changed-files-check
        if: needs.changed-files-check.outputs.any_changed == 'true'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with: 
                fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'
            - name: Install dependencies
              run: npm ci --legacy-peer-deps
            - name: Linting
              run: npx nx lint api
            - name: Build API
              run: npx nx build api
            - name: Create a Github release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx nx release --projects=api --skip-publish
    cd-api-status-check:
        if: always() && !cancelled()
        timeout-minutes: 1
        runs-on: ubuntu-latest
        needs: [changed-files-check, build-release]
        steps:
        - name: Fail job if any needs failed
          if: contains(needs.*.result, 'failure')
          run: exit 1